In [1]:
import numpy as np
from numpy import pi, cos, sin, linspace, meshgrid
import pyvista as pv
from itkwidgets import view

In [49]:
def x_(u, v):
    x = -2 + 2*cos(v) - cos(u)
    x[v<3*pi] = -2 + (2 + cos(u[v<3*pi]))*cos(v[v<3*pi])
    x[v<2*pi] = cos(u[v<2*pi])*(2.5 - 1.5*cos(v[v<2*pi]))
    return x

def y_(u, v):
    y = sin(u)
    y[v<2*pi] = sin(u[v<2*pi])*(2.5 - 1.5*cos(v[v<2*pi]))
    return y

def z_(u, v):
    z = -3*v + 12*pi
    z[v<3*pi] = (2 + cos(u[v<3*pi]))*sin(v[v<3*pi]) + 3*pi
    z[v<2*pi] = 3*v[v<2*pi] - 3*pi
    z[v<pi] = -2.5*sin(v[v<pi])
    return -z

 
u = linspace(pi, 2*pi, 10)
v = linspace(0, 4*pi, 38)
u, v = meshgrid(u, v)

x = x_(u, v)
y = y_(u, v)
z = z_(u, v)

In [50]:
grid = pv.StructuredGrid(x, y, z)
grid["z"] = z.T.ravel()
view(geometries=grid, cmap="Plasma (matplotlib)")

Viewer(cmap='Plasma (matplotlib)', geometries=[{'vtkClass': 'vtkPolyData', 'points': {'vtkClass': 'vtkPoints',…

In [2]:
object = pv.read("test_cavity_new.vtk")

In [53]:
p = pv.Plotter()

In [3]:
view(geometries=object)

Viewer(geometries=[{'vtkClass': 'vtkPolyData', 'points': {'vtkClass': 'vtkPoints', 'name': '_points', 'numberO…

In [38]:
mesh.getElements()

(array([ 1,  2, 15], dtype=int32),
 [array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
         22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
         39, 40, 41, 42, 43, 44], dtype=uint64),
  array([ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
          58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
          71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
          97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
         110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
         123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
         136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
         149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
         162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
         175, 176, 177

In [38]:
mesh.getElements()

(array([ 1,  2, 15], dtype=int32),
 [array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
         22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
         39, 40, 41, 42, 43, 44], dtype=uint64),
  array([ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
          58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
          71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
          97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
         110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
         123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
         136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
         149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
         162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
         175, 176, 177

In [ ]:
T(x+h) = T(x) + ( T'(x) ) * h + ( T''(x)/2! ) * h**2

In [ ]:
import gmsh
import gmsh_api
gmsh.initialize()
gmsh.model.add("square")
gmsh.model.geo.addPoint(0, 0, 0, 0.1, 1)
gmsh.model.geo.addPoint(1, 0, 0, 0.1, 2)
gmsh.model.geo.addPoint(1, 1, 0, 0.1, 3)
gmsh.model.geo.addPoint(0, 1, 0, 0.1, 4)
gmsh.model.geo.addLine(1, 2, 1)
gmsh.model.geo.addLine(2, 3, 2)
gmsh.model.geo.addLine(3, 4, 3)
# try automatic assignement of tag
line4 = gmsh.model.geo.addLine(4, 1)
gmsh.model.geo.addCurveLoop([1, 2, 3, line4], 1)
gmsh.model.geo.addPlaneSurface([1], 6)
gmsh.model.geo.synchronize()
gmsh.model.mesh.generate(2)
gmsh.write("square_testing_gmsh_python.msh")
# gmsh.finalize()


In [ ]:
mesh = gmsh_api.Mesh.from_gmsh(gmsh)

In [ ]:
mesh.nodes

In [ ]:
ls

In [ ]:
mesh=gmsh_api.Mesh.from_gmsh("mesh_simple_square.msh")

In [ ]:
import meshio

In [ ]:
ls

In [ ]:
mesh = meshio.read("mesh_simple_square.msh")

In [ ]:
mesh.

In [ ]:
mesh = gmsh.model.mesh
vtags,vxyz,_ = mesh.getNodes()

In [ ]:
ls

In [ ]:
gmsh.open("mesh_simple_square.geo")

In [ ]:
gmsh.model.mesh.getElements()

In [ ]:
gmsh.finalize()

In [ ]:
pts.reshape((pts.size//3,3))

In [ ]:
type(mesh.elements.values)

In [ ]:
type(mesh.nodes["x"])

In [ ]:
import pyvista as pv

mesh = pv.read("square_testing_gmsh_python.msh")

In [ ]:
view(geometries=mesh)

In [ ]:
p = pv.Plotter()
p.add_mesh(mesh)
p.show()

In [1]:
# pip install gmsh-sdk gmsh-api
import gmsh
import gmsh_api


In [2]:
gmsh.initialize()

In [3]:
gmsh.open("mesh_simple_square.geo")

In [4]:
mesh = gmsh.model.mesh

In [6]:
tags, coord, _ = mesh.getNodes()

In [7]:
tags

array([   1,    2,    3, ..., 3719, 3720, 3721], dtype=uint64)

In [8]:
coord = coord.reshape((coord.size//3,3))

In [9]:
coord

array([[-0.5       ,  0.5       ,  0.        ],
       [-0.5       , -0.5       ,  0.        ],
       [ 0.5       ,  0.5       ,  0.        ],
       ...,
       [ 0.45      , -0.48333333,  0.        ],
       [ 0.46666667, -0.48333333,  0.        ],
       [ 0.48333333, -0.48333333,  0.        ]])

In [34]:
gmsh.model.getPhysicalName(*gmsh.model.getPhysicalGroups()[5])

'fluid'

In [35]:
a = (3,"hello",3.8)

In [40]:
print(*a)

3 hello 3.8


In [41]:
print( 3, "hello", 3.8 )

3 hello 3.8


In [47]:
print(*gmsh.model.getPhysicalGroups()[0])

0 200


In [43]:
gmsh.model.getPhysicalName()

TypeError: getPhysicalName() missing 2 required positional arguments: 'dim' and 'tag'

In [ ]:
import pyvista as pv
