In [1]:
import numpy as np

In [2]:
fulldir3 = np.load('../../build/data/v1.0/fulldir_n3_m10.npy')
fulldir3

array([[ 1,  1,  1],
       [ 1,  1,  2],
       [ 1,  2,  2],
       [ 2,  2,  2],
       [ 1,  1,  3],
       [ 1,  2,  3],
       [ 2,  2,  3],
       [ 1,  3,  3],
       [ 2,  3,  3],
       [ 3,  3,  3],
       [ 1,  1,  4],
       [ 1,  2,  4],
       [ 2,  2,  4],
       [ 1,  3,  4],
       [ 2,  3,  4],
       [ 3,  3,  4],
       [ 1,  4,  4],
       [ 2,  4,  4],
       [ 3,  4,  4],
       [ 4,  4,  4],
       [ 1,  1,  5],
       [ 1,  2,  5],
       [ 2,  2,  5],
       [ 1,  3,  5],
       [ 2,  3,  5],
       [ 3,  3,  5],
       [ 1,  4,  5],
       [ 2,  4,  5],
       [ 3,  4,  5],
       [ 4,  4,  5],
       [ 1,  5,  5],
       [ 2,  5,  5],
       [ 3,  5,  5],
       [ 4,  5,  5],
       [ 5,  5,  5],
       [ 1,  1,  6],
       [ 1,  2,  6],
       [ 2,  2,  6],
       [ 1,  3,  6],
       [ 2,  3,  6],
       [ 3,  3,  6],
       [ 1,  4,  6],
       [ 2,  4,  6],
       [ 3,  4,  6],
       [ 4,  4,  6],
       [ 1,  5,  6],
       [ 2,  5,  6],
       [ 3,  

In [5]:
ndirs3 = np.load('../../build/data/v1.0/ndirs_n3_m10.npy')
ndirs3

array([  0,   1,   4,  10,  20,  35,  56,  84, 120, 165, 220],
      dtype=uint64)

In [6]:
multtabl3_0 = np.load('../../build/data/v1.0/multtabl_n3_m10_0.npy')
multtabl3_0

array([[  0,   1,   2,   4,   5,   7,  10,  11,  13,  16,  20,  21,  23,
         26,  30,  35,  36,  38,  41,  45,  50,  56,  57,  59,  62,  66,
         71,  77,  84,  85,  87,  90,  94,  99, 105, 112, 120, 121, 123,
        126, 130, 135, 141, 148, 156, 165, 166, 168, 171, 175, 180, 186,
        193, 201, 210],
       [  1,   2,   3,   5,   6,   8,  11,  12,  14,  17,  21,  22,  24,
         27,  31,  36,  37,  39,  42,  46,  51,  57,  58,  60,  63,  67,
         72,  78,  85,  86,  88,  91,  95, 100, 106, 113, 121, 122, 124,
        127, 131, 136, 142, 149, 157, 166, 167, 169, 172, 176, 181, 187,
        194, 202, 211],
       [  4,   5,   6,   7,   8,   9,  13,  14,  15,  18,  23,  24,  25,
         28,  32,  38,  39,  40,  43,  47,  52,  59,  60,  61,  64,  68,
         73,  79,  87,  88,  89,  92,  96, 101, 107, 114, 123, 124, 125,
        128, 132, 137, 143, 150, 158, 168, 169, 170, 173, 177, 182, 188,
        195, 203, 212],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,

In [7]:
multtabl3_0.shape


(10, 55)

In [9]:
multtabl3_0[:3,:6]

array([[0, 1, 2, 4, 5, 7],
       [1, 2, 3, 5, 6, 8],
       [4, 5, 6, 7, 8, 9]], dtype=uint64)

In [16]:
6//2

3

In [28]:
# How to determine the number of multiplication tables given the order:

for n in range(1,11):
    print()
    n_multtabl = n//2
    print("For order",n,", the total number of multtabl is", n_multtabl, "and are subdivided as follows:")
    for i in range(1,n//2+1):
        print("->",i,"+", n-i, "is", n)



For order 1 , the total number of multtabl is 0 and are subdivided as follows:

For order 2 , the total number of multtabl is 1 and are subdivided as follows:
-> 1 + 1 is 2

For order 3 , the total number of multtabl is 1 and are subdivided as follows:
-> 1 + 2 is 3

For order 4 , the total number of multtabl is 2 and are subdivided as follows:
-> 1 + 3 is 4
-> 2 + 2 is 4

For order 5 , the total number of multtabl is 2 and are subdivided as follows:
-> 1 + 4 is 5
-> 2 + 3 is 5

For order 6 , the total number of multtabl is 3 and are subdivided as follows:
-> 1 + 5 is 6
-> 2 + 4 is 6
-> 3 + 3 is 6

For order 7 , the total number of multtabl is 3 and are subdivided as follows:
-> 1 + 6 is 7
-> 2 + 5 is 7
-> 3 + 4 is 7

For order 8 , the total number of multtabl is 4 and are subdivided as follows:
-> 1 + 7 is 8
-> 2 + 6 is 8
-> 3 + 5 is 8
-> 4 + 4 is 8

For order 9 , the total number of multtabl is 4 and are subdivided as follows:
-> 1 + 8 is 9
-> 2 + 7 is 9
-> 3 + 6 is 9
-> 4 + 5 is 9
