## `sparse` Tutorial 03: Linear algebra support.

```
Contributors:
    Mauricio Aristizabal
        University of Texas at San Antonio
        Universidad EAFIT, Colombia.

Date of creation:  Jun 19 2024
Last modification: Jun 19 2024
```

### Introduction

The main purpose of the Order Truncated Imaginary (OTI) numbers was to provide an efficient method for computing arbitrary-order derivatives in Finite Element applications. Finite Element analysis is highly dependent on linear algbera operations, thus it was fundamental to develop an efficient interface to linear algebra, including vector and matrix operations. 

This document shows applications of `pyoti` for the computation of linear-algebra related operations.

For this, first import the libraries required.

In [1]:
import pyoti.sparse as oti  # Import the library.
import numpy as np

# Set to print all components
# oti.set_printoptions(terms_print=-1)

### Array class - `matso`.

The support for linear algebra operations is provided by the definition of an array class. The array class is named 'MATrix of Sparse Otis' `matso`. As its name suggest, its fundamental mode of operation is as a matrix element. Thus this class always consider the behavior as a rank-2 array.

Although this class has its own constructor, `pyoti` provides a numpy-like array creation functions that allow an easy migration to the new class.

An array that can hold an OTI number can be created in multiple ways. Here will be discussed a few of them.

#### Filled constructors

An array can be created using equivalent `zeros` or `ones` function, like with numpy. For instance, creating a 2x2 array of zeroes is created using the function `zeros(shape,**kwargs)`, with shape being an integer or a list with up-to 2 elements defining the shape of the array.

In [11]:
X = oti.zeros((2,2))
print(X)

matso< shape: (2, 2), 
 - Column 0
(0,0) 0
(1,0) 0
 - Column 1
(0,1) 0
(1,1) 0
>


Remarks:

- The number of dimensions of a matso is always 2.
- Printing a matso array gives  its shape and the contents are listed by columns.
- It may be more convenient to print only the real part of the matso array. The real part can be extracted with the "attribute" `real`. This returns a numpy array with the real coefficients of the matso array.


In [14]:
print(X.real)
print(type(X.real))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


Other constructors are shown below:

In [19]:
print('"ones" constructor:')
print( oti.ones( ( 2, 2 ) ).real )
print()
print('"eye" constructor:')
print( oti.eye( 2, ).real  )

"ones" constructor:
[[1. 1.]
 [1. 1.]]

"eye" constructor:
[[1. 0.]
 [0. 1.]]
