In [1]:
import sys
path2oti = '../../../build/'
sys.path.append(path2oti) # Add path to OTI library.

import pyoti.real   as r
import pyoti.sparse as oti
import pyoti.core   as coti

np = oti.np

e = oti.e

import scipy as scp
import sympy as sym

xs, ys , zs = sym.symbols('x y z')

In [74]:
import numpy as np
import scipy.linalg as spla

ka = 0.5*np.pi
m=1
h=1e-10
c = 1
ka_m = np.array([[ka,0,0,0],
                 [0,ka,0,0],
                 [0,0,ka,0],
                 [0,0,0,ka] ])

m_m =  np.array([[m,0,0,0],
                 [0,m,0,0],
                 [0,0,m,0],
                 [0,0,0,m] ])

c_m =  np.array([[ c, 0,-h, 0],
                 [ 0, c, 0,-h],
                 [ h, 0, c, 0],
                 [ 0, h, 0, c] ])

i2_m = np.array([[ 0,-1, 0, 0],
                 [ 1, 0, 0, 0],
                 [ 0, 0, 0,-1],
                 [ 0, 0, 1, 0] ])


one_m =  np.array([[1,0,0,0],
                   [0,1,0,0],
                   [0,0,1,0],
                   [0,0,0,1] ])


a = np.dot( c_m , ( spla.expm( np.dot(i2_m,ka_m) ) + spla.expm( -np.dot(i2_m,ka_m) ) - one_m*2 ) )
b = m_m

eigval,eigvec = spla.eig(a,b=b)


S = -np.dot(spla.inv(b),a)
for i in range(2):
    Q,R = spla.qr(S)
    S = Q.T@S@Q


print("Resulting eigenvalues:")
print(eigval)

Resulting eigenvalues:
[-2.+2.e-10j -2.-2.e-10j -2.+2.e-10j -2.-2.e-10j]


In [75]:
S

array([[ 2.e+00,  0.e+00, -2.e-10,  0.e+00],
       [ 0.e+00,  2.e+00,  0.e+00, -2.e-10],
       [ 2.e-10,  0.e+00,  2.e+00,  0.e+00],
       [ 0.e+00,  2.e-10,  0.e+00,  2.e+00]])

In [76]:
R@Q

array([[ 2.e+00,  0.e+00, -2.e-10,  0.e+00],
       [ 0.e+00,  2.e+00,  0.e+00, -2.e-10],
       [ 2.e-10,  0.e+00,  2.e+00,  0.e+00],
       [ 0.e+00,  2.e-10,  0.e+00,  2.e+00]])

In [19]:
S

array([[ 4.e+00,  4.e-10,  0.e+00,  0.e+00],
       [-4.e-10,  4.e+00,  0.e+00,  0.e+00],
       [ 0.e+00,  0.e+00,  4.e+00,  4.e-10],
       [ 0.e+00,  0.e+00, -4.e-10,  4.e+00]])

In [2]:
eigval,eigvec = spla.eig(a,b=b)

In [3]:
eigval

array([4.+4.e-10j, 4.-4.e-10j, 4.+4.e-10j, 4.-4.e-10j])

In [7]:
eigvec

array([[-0.32564071-0.35083544j, -0.32564071+0.35083544j,
         0.51613355-0.48014792j,  0.51613355+0.48014792j],
       [-0.35083544+0.32564088j, -0.35083544-0.32564088j,
        -0.48014841-0.51613425j, -0.48014841+0.51613425j],
       [-0.27360073-0.44273572j, -0.27360073+0.44273572j,
        -0.05515291+0.00465471j, -0.05515291-0.00465471j],
       [-0.44273564+0.27360191j, -0.44273564-0.27360191j,
         0.00465487+0.05515342j,  0.00465487-0.05515342j]])

In [38]:
deriv = 2/m*np.sin(ka/2)**2
deriv

2.0

In [39]:
2*c/m*np.sin(ka/2)**2

2.0

In [46]:
import numpy as np
import scipy.linalg as spla

ka = 0.5*np.pi
m=1
h=1e-10
c = 1
ka_m = np.array([[ka,0],
                 [0,ka]
                ])

m_m =  np.array([[m,0],
                 [0,m] ])

c_m =  np.array([[c,-h ],
                 [h, c ] ])

i2_m = np.array([[0,-1],
                 [1, 0] ])


one_m =  np.array([[1,0],
                   [0,1] ])


a = np.dot(c_m,(spla.expm(1j*ka_m)+spla.expm(-1j*ka_m)-one_m*2))

b = -m_m

# Falla esta parte por 
# eigval,eigvec = spla.eigs(a,b=b)
S = -np.dot(spla.inv(b),a)
# AA,BB,Q,Z = spla.qz(a,b)
Q,R = spla.qr(S)


print(Q)

print(R)

[[-1.e+00+0.j -1.e-10+0.j]
 [-1.e-10-0.j  1.e+00+0.j]]
[[ 2.+0.j  0.+0.j]
 [ 0.+0.j -2.+0.j]]


In [47]:
a

array([[-2.e+00+0.j,  2.e-10+0.j],
       [-2.e-10+0.j, -2.e+00+0.j]])

In [48]:
b

array([[-1,  0],
       [ 0, -1]])

In [49]:
eigval,eigvec = scp.linalg.eig(a,b=b)

LinAlgError: generalized eig algorithm (ggev) did not converge (LAPACK info=2)

In [44]:
# QR Algorithm:

A = np.ones((5,5))

for i in range(A.shape[0]):
    for j in range(A.shape[0]):
        A[i,j]=(i+1)**(A.shape[0]-j-1)
    # end for 
# end for

S = A.copy()
U = np.eye(A.shape[0])
for i in range(2000):
    Q,R=spla.qr(S)
    S = Q.T@S@Q
    U = U@Q
    
    
np.set_printoptions(linewidth=120)
S

array([[ 4.59604348e+001,  3.33071694e+002, -5.14756163e+002,  3.07720023e+002, -6.67935827e+001],
       [-1.03753786e-322, -2.89437019e+001,  6.29178024e+001, -4.74504322e+001,  1.26877402e+001],
       [ 1.48219694e-323,  3.95252517e-323,  6.79538792e+000, -9.37453655e+000,  3.58763723e+000],
       [-1.13635099e-322,  1.13635099e-322, -4.94065646e-324, -8.49619485e-001,  6.47286094e-001],
       [-1.67982320e-322,  1.08694442e-322,  0.00000000e+000,  0.00000000e+000,  3.74986442e-002]])

In [45]:
spla.eig(A)[0]-np.diag(S)

array([-1.63424829e-13+0.j, -1.10134124e-13+0.j, -1.59872116e-14+0.j,  2.99760217e-15+0.j, -1.52655666e-16+0.j])

In [35]:
U.T@S@U

array([[ 3.44995641e-01,  4.94458137e-01, -4.40946116e+00,  2.16106110e+00,  1.50533436e+01],
       [ 1.71871402e+00,  8.97942822e+00, -3.48792726e+01,  4.41779825e+01,  1.90352112e+02],
       [-2.38155346e+00, -2.03897363e+01,  6.00204360e+01, -1.19131380e+02, -4.42488930e+02],
       [ 1.73742634e+00,  1.70207452e+01, -4.60607514e+01,  1.22783793e+02,  4.26674155e+02],
       [-6.24965819e-01, -5.65759189e+00,  1.70126762e+01, -4.81269517e+01, -1.69128653e+02]])