In [6]:
import scipy.sparse as spr
import sys
path2oti = '../../../build/'
sys.path.append(path2oti) # Add path to OTI library.

import pyoti.sparse as oti 
import pyoti.core   as coti 
import pyoti.fem    as fem 
e  = oti.e
np = oti.np

import pyvista as pv
p = pv.BackgroundPlotter()

In [7]:
Th = fem.square(2,1,he = 1/5, element_order=2, structured = False, quads=True, save=True)

grid = Th.to_pv(dims=2)

p.clear()
p.add_mesh(grid, name='grid',show_edges=True, parallel_projection=True,grid = True)

/Users/maristi7/opt/anaconda3/envs/pyoti/lib/python3.7/site-packages/numpy/ctypeslib.py:523: RuntimeWarning: A builtin ctypes object gave a PEP3118 format string that does not match its itemsize, so a best-guess will be made of the data type. Newer versions of python may behave correctly.
  return array(obj, copy=False)


(vtkRenderingOpenGL2Python.vtkOpenGLActor)0x7f9316964a08

In [8]:
Th.nodes[:,0].shape
x = oti.array(Th.nodes[:,0])
print((x+x*oti.e(1))**2)

matso< shape: (249, 1), 
 - Column 0
(0,0) 1 + 2 * e([1])
(1,0) 1 + 2 * e([1])
(2,0) 1 + 2 * e([1])
(3,0) 1 + 2 * e([1])
(4,0) 1 + 2 * e([1])
(5,0) 1 + 2 * e([1])
(6,0) 1 + 2 * e([1])
(7,0) 1 + 2 * e([1])
(8,0) 1 + 2 * e([1])
(9,0) 1 + 2 * e([1])
(10,0) 1 + 2 * e([1])
(11,0) 1 + 2 * e([1])
(12,0) 1 + 2 * e([1])
(13,0) 1 + 2 * e([1])
(14,0) 1 + 2 * e([1])
(15,0) 0.64 + 1.28 * e([1])
(16,0) 0.36 + 0.72 * e([1])
(17,0) 0.16 + 0.32 * e([1])
(18,0) 0.04 + 0.08 * e([1])
(19,0) 7.57484e-24 + 1.51497e-23 * e([1])
(20,0) 0.04 + 0.08 * e([1])
(21,0) 0.16 + 0.32 * e([1])
(22,0) 0.36 + 0.72 * e([1])
(23,0) 0.64 + 1.28 * e([1])
(24,0) 0.81 + 1.62 * e([1])
(25,0) 0.49 + 0.98 * e([1])
(26,0) 0.25 + 0.5 * e([1])
(27,0) 0.09 + 0.18 * e([1])
(28,0) 0.01 + 0.02 * e([1])
(29,0) 0.01 + 0.02 * e([1])
(30,0) 0.09 + 0.18 * e([1])
(31,0) 0.25 + 0.5 * e([1])
(32,0) 0.49 + 0.98 * e([1])
(33,0) 0.81 + 1.62 * e([1])
(34,0) 1 + 2 * e([1])
(35,0) 1 + 2 * e([1])
(36,0) 1 + 2 * e([1])
(37,0) 1 + 2 * e([1])
(38,0) 1 + 

In [9]:
x = oti.array(Th.nodes[:,0])
y = oti.array(Th.nodes[:,1])
x = x+y*oti.e(1)
y = y+x*oti.e(1)
val = x**2+y**2

In [10]:
val


matso< shape: (249, 1), 
 - Column 0
(0,0) 0.5 - 1 * e([1])
(1,0) 0.5 + 1 * e([1])
(2,0) 0.5 + 1 * e([1])
(3,0) 0.5 - 1 * e([1])
(4,0) 0.222222 - 0.666667 * e([1])
(5,0) 0.0555556 - 0.333333 * e([1])
(6,0) 3.78742e-24 - 2.75224e-12 * e([1])
(7,0) 0.0555556 + 0.333333 * e([1])
(8,0) 0.222222 + 0.666667 * e([1])
(9,0) 0.347222 - 0.833333 * e([1])
(10,0) 0.125 - 0.5 * e([1])
(11,0) 0.0138889 - 0.166667 * e([1])
(12,0) 0.0138889 + 0.166667 * e([1])
(13,0) 0.125 + 0.5 * e([1])
(14,0) 0.347222 + 0.833333 * e([1])
(15,0) 0.5 + 0.8 * e([1])
(16,0) 0.5 + 0.6 * e([1])
(17,0) 0.5 + 0.4 * e([1])
(18,0) 0.5 + 0.2 * e([1])
(19,0) 0.5 + 2.75224e-12 * e([1])
(20,0) 0.5 - 0.2 * e([1])
(21,0) 0.5 - 0.4 * e([1])
(22,0) 0.5 - 0.6 * e([1])
(23,0) 0.5 - 0.8 * e([1])
(24,0) 0.5 + 0.9 * e([1])
(25,0) 0.5 + 0.7 * e([1])
(26,0) 0.5 + 0.5 * e([1])
(27,0) 0.5 + 0.3 * e([1])
(28,0) 0.5 + 0.1 * e([1])
(29,0) 0.5 - 0.1 * e([1])
(30,0) 0.5 - 0.3 * e([1])
(31,0) 0.5 - 0.5 * e([1])
(32,0) 0.5 - 0.7 * e([1])
(33,0) 0.5 

In [11]:
inval = val.real
grid = Th.to_pv(  pd = [inval], pd_names=['val'])
grid2 = grid.warp_by_scalar(factor = 0.5)
p.clear()
p.add_mesh(grid2, show_edges=True)

(vtkRenderingOpenGL2Python.vtkOpenGLActor)0x7f93169649a8

In [19]:
inval = val.taylor_integrate([1],[1.0]).real

In [22]:
grid = Th.to_pv(  pd = [inval], pd_names=['val'])
grid3 = grid.warp_by_scalar(factor = 0.5)
# p.clear()
p.add_mesh(grid3, show_edges=True,parallel_projection = True, grid=True)

(vtkRenderingOpenGL2Python.vtkOpenGLActor)0x7fb8846e72e8

In [8]:
Th.export('plate.vtk',pd=[val.taylor_integrate([1],[0.01]).real],pd_names=['val'])

In [13]:
%timeit Y = oti.array( 3+oti.e(1) )

6.01 µs ± 209 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
Y = oti.array( [[3+oti.e(1,order=2)],[4+oti.e(100,order=2)]] )

In [ ]:
oti.det(Y**2)

In [8]:
np.array(3)

array(3)

In [1]:
Y = np.array([[1,2,3],[4,5,6]])

NameError: name 'np' is not defined

In [8]:
Y.item(0)

1

In [9]:
Th2 = fem.mesh.load('cruciform.msh')

In [13]:
Th2.group_names['']

{'dim': 2,
 'id': 5,
 'entities': array([1], dtype=int32),
 'members': [{'types': array([9], dtype=int32),
   'tags': [array([ 342,  343,  344, ..., 5989, 5990, 5991], dtype=uint64)],
   'nodes': [array([[ 1713,    95,    94,  3356,   258,  3357],
           [  134,  1769,   135,  3358,  3359,   298],
           [ 2166,    29,  1465,  3360,  3361,  3362],
           ...,
           [ 1071,  1345,  1310, 10728, 10959,  5063],
           [ 1184,  1622,  1293,  7596, 10116,  4211],
           [ 1452,  1680,  2188,  5146, 11638, 11480]], dtype=uint64)]}]}

In [17]:
Th2.group_names['crack_path']


{'dim': 1,
 'id': 100,
 'entities': array([41, 42], dtype=int32),
 'members': [{'types': array([8], dtype=int32),
   'tags': [array([ 14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
            27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
            40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
            53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
            66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
            79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
            92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
           105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
           118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
           131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
           144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
           157, 158, 159, 160, 161, 162, 1

In [4]:
Th.get_all_elements_pd()


Dim   Type Tag                             Nodes
1    0  point   1                               [0]
2    0  point   2                               [1]
3    0  point   3                               [2]
4    0  point   4                               [3]
5    1  line3   5                         [0, 4, 5]
6    1  line3   6                         [4, 1, 6]
7    1  line3   7                         [1, 7, 8]
8    1  line3   8                         [7, 3, 9]
9    1  line3   9                       [3, 10, 11]
10   1  line3  10                       [10, 2, 12]
11   1  line3  11                       [2, 13, 14]
12   1  line3  12                       [13, 0, 15]
13   2  quad8  13     [1, 18, 17, 4, 19, 20, 21, 6]
14   2  quad8  14  [13, 17, 18, 16, 22, 20, 23, 24]
15   2  quad8  15     [16, 18, 1, 7, 23, 19, 8, 25]
16   2  quad8  16     [13, 0, 4, 17, 15, 5, 21, 22]
17   2  quad8  17   [16, 10, 2, 13, 26, 12, 14, 24]
18   2  quad8  18     [16, 7, 3, 10, 25, 9, 11, 26]

In [7]:
Th2.get_all_elements_pd()

Dim   Type   Tag                                   Nodes
1      0  point     1                                     [0]
2      1  line3     2                               [1, 3, 5]
3      1  line3     3                               [3, 4, 6]
4      1  line3     4                               [4, 2, 7]
5      1  line3     5                             [8, 10, 12]
...   ..    ...   ...                                     ...
5987   2   tri6  5987  [1015, 1025, 1465, 11678, 11680, 5092]
5988   2   tri6  5988   [1025, 1464, 1465, 6777, 3390, 11680]
5989   2   tri6  5989  [1071, 1345, 1310, 10728, 10959, 5063]
5990   2   tri6  5990   [1184, 1622, 1293, 7596, 10116, 4211]
5991   2   tri6  5991  [1452, 1680, 2188, 5146, 11638, 11480]

[5991 rows x 4 columns]

In [16]:
Th2.groups

[None,
 None,
 None,
 None,
 [0, 1],
 [1, 10],
 [1, 20],
 [1, 30],
 [1, 40],
 [1, 100],
 [2, 5]]

In [17]:
surface = Th2.to_pv(dims=2)
lines   = Th2.to_pv(dims=1)

p.clear()

p.add_mesh(surface, show_edges=True, grid = True)
p.add_mesh(lines, linewidth=10, color=(0,1,0))


(vtkRenderingOpenGL2Python.vtkOpenGLActor)0x7fe7c6a29468

In [7]:
Th.get_all_elements()

array([[0, 'point', 1, array([0], dtype=uint64)],
       [0, 'point', 2, array([1], dtype=uint64)],
       [0, 'point', 3, array([2], dtype=uint64)],
       [0, 'point', 4, array([3], dtype=uint64)],
       [1, 'line3', 5, array([0, 4, 5], dtype=uint64)],
       [1, 'line3', 6, array([4, 1, 6], dtype=uint64)],
       [1, 'line3', 7, array([1, 7, 8], dtype=uint64)],
       [1, 'line3', 8, array([7, 3, 9], dtype=uint64)],
       [1, 'line3', 9, array([ 3, 10, 11], dtype=uint64)],
       [1, 'line3', 10, array([10,  2, 12], dtype=uint64)],
       [1, 'line3', 11, array([ 2, 13, 14], dtype=uint64)],
       [1, 'line3', 12, array([13,  0, 15], dtype=uint64)],
       [2, 'quad8', 13,
        array([ 1, 18, 17,  4, 19, 20, 21,  6], dtype=uint64)],
       [2, 'quad8', 14,
        array([13, 17, 18, 16, 22, 20, 23, 24], dtype=uint64)],
       [2, 'quad8', 15,
        array([16, 18,  1,  7, 23, 19,  8, 25], dtype=uint64)],
       [2, 'quad8', 16,
        array([13,  0,  4, 17, 15,  5, 21, 22], d

In [9]:
elems = Th.elements


In [18]:
elems[2]['nodes'][0]

array([[ 1, 18, 17,  4, 19, 20, 21,  6],
       [13, 17, 18, 16, 22, 20, 23, 24],
       [16, 18,  1,  7, 23, 19,  8, 25],
       [13,  0,  4, 17, 15,  5, 21, 22],
       [16, 10,  2, 13, 26, 12, 14, 24],
       [16,  7,  3, 10, 25,  9, 11, 26]], dtype=uint64)

In [18]:
import gmsh

In [19]:
gmsh.initialize()
gmsh.open('./square.msh')

In [20]:
gmsh.model.mesh.generate()

In [21]:
gmsh.finalize()

In [12]:
A = {}
A[(2,150)] = {"hey":"Hello"}


In [13]:
A[(2,150)]

{'hey': 'Hello'}