In [2]:
# 1. SET GLOBAL PATH 
import sys
path2oti = '../../../build'
sys.path.append(path2oti) # Add path to OTI library.

import pyoti.dense as oti
np = oti.np
eps = oti.e

In [7]:
# Change print options.

oti.print_options['im_obj_separator'] = " "
oti.print_options['term_separator']   = "*"

In [10]:

num = oti.otibase(3,nbases=2,dtype = float,zero = 10)

In [11]:
num

10 +e([1])*10 +e([2])*10 +e([[1,2]])*10 +e([1,2])*10 +e([[2,2]])*10 +e([[1,3]])*10 +e([[1,2],2])*10 +e([1,[2,2]])*10 +e([[2,3]])*10

In [12]:
-num

-10 +e([1])*-10 +e([2])*-10 +e([[1,2]])*-10 +e([1,2])*-10 +e([[2,2]])*-10 +e([[1,3]])*-10 +e([[1,2],2])*-10 +e([1,[2,2]])*-10 +e([[2,3]])*-10

In [13]:
isinstance(num,oti.otibase)

True

In [14]:
num.dtype

float

In [15]:
num.p_im[0].dtype

dtype('O')

In [16]:
num2 = oti.otibase(3, nbases=2, dtype = np.ndarray, zero=np.ones((2,1)))

In [17]:
-num2

[[-1.]
 [-1.]] +e([1])*[[-1.]
 [-1.]] +e([2])*[[-1.]
 [-1.]] +e([[1,2]])*[[-1.]
 [-1.]] +e([1,2])*[[-1.]
 [-1.]] +e([[2,2]])*[[-1.]
 [-1.]] +e([[1,3]])*[[-1.]
 [-1.]] +e([[1,2],2])*[[-1.]
 [-1.]] +e([1,[2,2]])*[[-1.]
 [-1.]] +e([[2,3]])*[[-1.]
 [-1.]]

In [18]:
num2[0,0]

1.0 +e([1])*1.0 +e([2])*1.0 +e([[1,2]])*1.0 +e([1,2])*1.0 +e([[2,2]])*1.0 +e([[1,3]])*1.0 +e([[1,2],2])*1.0 +e([1,[2,2]])*1.0 +e([[2,3]])*1.0

In [19]:
num2.p_im[1]

array([array([[1.],
       [1.]]), array([[1.],
       [1.]]),
       array([[1.],
       [1.]])], dtype=object)

In [12]:
num.re+num2.re

array([[11.],
       [11.]])

In [13]:

num.p_im[0][0]+num2.p_im[0][0]

array([[11.],
       [11.]])

In [14]:
num+num2

[[11.]
 [11.]]
+e([1])*
[[11.]
 [11.]]
+e([2])*
[[11.]
 [11.]]
+e([[1,2]])*
[[11.]
 [11.]]
+e([1,2])*
[[11.]
 [11.]]
+e([[2,2]])*
[[11.]
 [11.]]
+e([[1,3]])*
[[11.]
 [11.]]
+e([[1,2],2])*
[[11.]
 [11.]]
+e([1,[2,2]])*
[[11.]
 [11.]]
+e([[2,3]])*
[[11.]
 [11.]]

In [20]:
num2.empty_like()

None +e([1])*None +e([2])*None +e([[1,2]])*None +e([1,2])*None +e([[2,2]])*None +e([[1,3]])*None +e([[1,2],2])*None +e([1,[2,2]])*None +e([[2,3]])*None

In [16]:

#%timeit num+num2

In [21]:
4.5*num2

[[4.5]
 [4.5]] +e([1])*[[4.5]
 [4.5]] +e([2])*[[4.5]
 [4.5]] +e([[1,2]])*[[4.5]
 [4.5]] +e([1,2])*[[4.5]
 [4.5]] +e([[2,2]])*[[4.5]
 [4.5]] +e([[1,3]])*[[4.5]
 [4.5]] +e([[1,2],2])*[[4.5]
 [4.5]] +e([1,[2,2]])*[[4.5]
 [4.5]] +e([[2,3]])*[[4.5]
 [4.5]]

In [18]:

num*num2

[[10.]
 [10.]]
+e([1])*
[[20.]
 [20.]]
+e([2])*
[[20.]
 [20.]]
+e([[1,2]])*
[[30.]
 [30.]]
+e([1,2])*
[[40.]
 [40.]]
+e([[2,2]])*
[[30.]
 [30.]]
+e([[1,3]])*
[[40.]
 [40.]]
+e([[1,2],2])*
[[60.]
 [60.]]
+e([1,[2,2]])*
[[60.]
 [60.]]
+e([[2,3]])*
[[40.]
 [40.]]

In [22]:
num.getIm(oti.imdir([1]))

10

In [25]:
num.setIm(oti.imdir([1]),17)

In [26]:
num

3.5 +e([1])*17 +e([2])*3.5 +e([[1,2]])*3.5 +e([1,2])*3.5 +e([[2,2]])*3.5 +e([[1,3]])*3.5 +e([[1,2],2])*3.5 +e([1,[2,2]])*3.5 +e([[2,3]])*3.5

In [27]:
num = oti.otibase( 3, nbases=2, zero=3.5 )

In [28]:
# Mixing Scipy with OTI library:

import sympy as sym

f_r = sym.symbols('f_r')
f_e1 = sym.symbols('f_{e1}')
f_e2 = sym.symbols('f_{e2}')
f_e11 = sym.symbols('f_{e11}')
f_e12 = sym.symbols('f_{e12}')
f_e22 = sym.symbols('f_{e22}')
f_e111 = sym.symbols('f_{e111}')
f_e112 = sym.symbols('f_{e112}')
f_e122 = sym.symbols('f_{e122}')
f_e222 = sym.symbols('f_{e222}')


f_r = sym.symbols('f_r')
f_e1 = sym.symbols('f_{x}')
f_e2 = sym.symbols('f_{y}')
f_e11 = sym.symbols('f_{xx}')/2
f_e12 = sym.symbols('f_{xy}')
f_e22 = sym.symbols('f_{yy}')/2
f_e111 = sym.symbols('f_{xxx}')/6
f_e112 = sym.symbols('f_{xxy}')/2
f_e122 = sym.symbols('f_{xyy}')/2
f_e222 = sym.symbols('f_{yyy}')/6


In [29]:
f = oti.otibase(3,nbases=2)

f.re = f_r
f.p_im[0][0] = f_e1  # |
f.p_im[0][1] = f_e2  # | Order 1
f.p_im[1][0] = f_e11 # -
f.p_im[1][1] = f_e12 # | Order 2 
f.p_im[1][2] = f_e22 # -
f.p_im[2][0] = f_e111 # -
f.p_im[2][1] = f_e112 # |
f.p_im[2][2] = f_e122 # | Order 3
f.p_im[2][3] = f_e122 # -

In [30]:
f

f_r +e([1])*f_{x} +e([2])*f_{y} +e([[1,2]])*f_{xx}/2 +e([1,2])*f_{xy} +e([[2,2]])*f_{yy}/2 +e([[1,3]])*f_{xxx}/6 +e([[1,2],2])*f_{xxy}/2 +e([1,[2,2]])*f_{xyy}/2 +e([[2,3]])*f_{xyy}/2

In [25]:
f0 = f.copy()

In [26]:
f0_e1=f0.extractIm(oti.imdir([1]))
f0_e2=f0.extractIm(oti.imdir([2]))
f0.order -= 1

f1 = f0_e1+f0_e2*f0

In [28]:
f1.

f_r*f_{y} + f_{x}
+e([1])*
1.0*f_r*f_{xy} + 1.0*f_{xx} + f_{x}*f_{y}
+e([2])*
1.0*f_r*f_{yy} + 1.0*f_{xy} + f_{y}**2
+e([[1,2]])*
0.5*f_r*f_{xxy} + 0.5*f_{xxx} + f_{xx}*f_{y}/2 + 1.0*f_{xy}*f_{x}
+e([1,2])*
1.0*f_r*f_{xyy} + 1.0*f_{xxy} + 2.0*f_{xy}*f_{y} + 1.0*f_{x}*f_{yy}
+e([[2,2]])*
1.5*f_r*f_{xyy} + 0.5*f_{xyy} + 1.5*f_{yy}*f_{y}

In [29]:
f1_e1=f1.extractIm(oti.imdir([1]))
f1_e2=f1.extractIm(oti.imdir([2]))
f0.order -= 1

f2 = f1_e1+f1_e2*f0

In [30]:
f2

1.0*f_r*f_{xy} + f_r*(1.0*f_r*f_{yy} + 1.0*f_{xy} + f_{y}**2) + 1.0*f_{xx} + f_{x}*f_{y}
+e([1])*
1.0*f_r*f_{xxy} + f_r*(1.0*f_r*f_{xyy} + 1.0*f_{xxy} + 2.0*f_{xy}*f_{y} + 1.0*f_{x}*f_{yy}) + 1.0*f_{xxx} + 1.0*f_{xx}*f_{y} + 2.0*f_{xy}*f_{x} + f_{x}*(1.0*f_r*f_{yy} + 1.0*f_{xy} + f_{y}**2)
+e([2])*
1.0*f_r*f_{xyy} + f_r*(3.0*f_r*f_{xyy} + 1.0*f_{xyy} + 3.0*f_{yy}*f_{y}) + 1.0*f_{xxy} + 2.0*f_{xy}*f_{y} + 1.0*f_{x}*f_{yy} + f_{y}*(1.0*f_r*f_{yy} + 1.0*f_{xy} + f_{y}**2)

In [31]:
f2.re.expand()

1.0*f_r**2*f_{yy} + 2.0*f_r*f_{xy} + f_r*f_{y}**2 + 1.0*f_{xx} + f_{x}*f_{y}

In [32]:
f2_e1=f2.extractIm(oti.imdir([1]))
f2_e2=f2.extractIm(oti.imdir([2]))
f0.order -= 1

f3 = f2_e1+f2_e2*f0

In [33]:

f3

1.0*f_r*f_{xxy} + f_r*(1.0*f_r*f_{xyy} + 1.0*f_{xxy} + 2.0*f_{xy}*f_{y} + 1.0*f_{x}*f_{yy}) + f_r*(1.0*f_r*f_{xyy} + f_r*(3.0*f_r*f_{xyy} + 1.0*f_{xyy} + 3.0*f_{yy}*f_{y}) + 1.0*f_{xxy} + 2.0*f_{xy}*f_{y} + 1.0*f_{x}*f_{yy} + f_{y}*(1.0*f_r*f_{yy} + 1.0*f_{xy} + f_{y}**2)) + 1.0*f_{xxx} + 1.0*f_{xx}*f_{y} + 2.0*f_{xy}*f_{x} + f_{x}*(1.0*f_r*f_{yy} + 1.0*f_{xy} + f_{y}**2)

In [34]:
f3.re.expand()


3.0*f_r**3*f_{xyy} + 3.0*f_r**2*f_{xyy} + 4.0*f_r**2*f_{yy}*f_{y} + 3.0*f_r*f_{xxy} + 5.0*f_r*f_{xy}*f_{y} + 3.0*f_r*f_{x}*f_{yy} + f_r*f_{y}**3 + 1.0*f_{xxx} + 1.0*f_{xx}*f_{y} + 3.0*f_{xy}*f_{x} + f_{x}*f_{y}**2