In [1]:
import scipy.sparse as spr
import scipy.sparse.linalg as spla
from scipy.linalg import det as sp_det
import sys
path2oti = '../../../build/'
sys.path.append(path2oti) # Add path to OTI library.

import pyoti.real as r
np = r.np

In [2]:
import pyoti.fem as fem

In [3]:
Th.nodes

NameError: name 'Th' is not defined

In [4]:
dim = 3
nip = 27
b = r.number(4.5,nip=nip)

In [3]:
A = r.ones((3,3))


%timeit A*2

373 ns ± 5.19 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [13]:
b_np = np.ones(27)*4.5
%timeit np.sum(b_np*b_np)

5.7 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
%timeit r.gauss_integrate(b,b)

178 ns ± 2.83 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [15]:
I = r.eye(3, nip=nip)
I3 = I*3
res = r.zero(nip=nip)
%timeit r.det(I3,out=res)
%timeit r.det(I3)

3.73 µs ± 77.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.73 µs ± 32.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [35]:
res = A.copy()*3
%timeit A*A

194 ns ± 1.89 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [16]:
def det(K):
    nip = K.shape[0]
    res = np.zeros((nip,1,1))
    for i in range(nip):
        res[i,0,0]=np.linalg.det(K[i])
#         res[i,0,0]=sp_det(K[i])
    return res
        

In [17]:
I3_np = np.zeros((nip,3,3))
I = np.eye(3)*3
for i in range(nip):
    I3_np[i] = I
# end for 

%timeit det(I3_np)

289 µs ± 15.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [36]:
A_np = np.ones((3,3))*3
%timeit A_np*A_np


580 ns ± 8.88 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [60]:
%timeit (b**2)

801 ns ± 2.19 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [61]:
b_np = np.ones((nip,1,1))*4.5

In [62]:
%timeit (b_np**2)

977 ns ± 8.18 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [63]:
b[2]=5+10
b_np[2,:,:]=5+10

In [64]:
b

dnumfe< nip: 27, 
(0) 4.5
(1) 4.5
(2) 15.0
(3) 4.5
(4) 4.5
(5) 4.5
(6) 4.5
(7) 4.5
(8) 4.5
(9) 4.5
(10) 4.5
(11) 4.5
(12) 4.5
(13) 4.5
(14) 4.5
(15) 4.5
(16) 4.5
(17) 4.5
(18) 4.5
(19) 4.5
(20) 4.5
(21) 4.5
(22) 4.5
(23) 4.5
(24) 4.5
(25) 4.5
(26) 4.5
>

In [65]:
b_np

array([[[ 4.5]],

       [[ 4.5]],

       [[15. ]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]],

       [[ 4.5]]])

In [32]:
B = r.dmatfe((dim,dim),nip)

In [33]:
B = B+2

In [34]:
B

dmatfe< nip: 27, 
(Integration point - 0) 
-------------------------
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
-------------------------
(Integration point - 1) 
-------------------------
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
-------------------------
(Integration point - 2) 
-------------------------
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
-------------------------
(Integration point - 3) 
-------------------------
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
-------------------------
(Integration point - 4) 
-------------------------
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
-------------------------
(Integration point - 5) 
-------------------------
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
-------------------------
(Integration point - 6) 
-------------------------
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
-------------------------
(Integration point - 7) 
-------------------------
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
-------------------------
(Integration point - 8) 
-------------------------
[[2. 2. 2.]
 [2. 2.

In [35]:
B**2

dmatfe< nip: 27, 
(Integration point - 0) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 1) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 2) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 3) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 4) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 5) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 6) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 7) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 8) 
-------------------------
[[4. 4. 4.]
 [4. 4.

In [73]:
%timeit B+2

4.87 µs ± 75.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [74]:
B_np = np.zeros((nip,dim,dim))+2

In [75]:
%timeit B_np+2

1.32 µs ± 13.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [76]:
%timeit b+B

4.96 µs ± 69.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [77]:
b+B

dmatfe< nip: 27, 
(Integration point - 0) 
-------------------------
[[6.5 6.5 6.5]
 [6.5 6.5 6.5]
 [6.5 6.5 6.5]]
-------------------------
(Integration point - 1) 
-------------------------
[[6.5 6.5 6.5]
 [6.5 6.5 6.5]
 [6.5 6.5 6.5]]
-------------------------
(Integration point - 2) 
-------------------------
[[17. 17. 17.]
 [17. 17. 17.]
 [17. 17. 17.]]
-------------------------
(Integration point - 3) 
-------------------------
[[6.5 6.5 6.5]
 [6.5 6.5 6.5]
 [6.5 6.5 6.5]]
-------------------------
(Integration point - 4) 
-------------------------
[[6.5 6.5 6.5]
 [6.5 6.5 6.5]
 [6.5 6.5 6.5]]
-------------------------
(Integration point - 5) 
-------------------------
[[6.5 6.5 6.5]
 [6.5 6.5 6.5]
 [6.5 6.5 6.5]]
-------------------------
(Integration point - 6) 
-------------------------
[[6.5 6.5 6.5]
 [6.5 6.5 6.5]
 [6.5 6.5 6.5]]
-------------------------
(Integration point - 7) 
-------------------------
[[6.5 6.5 6.5]
 [6.5 6.5 6.5]
 [6.5 6.5 6.5]]
------------------------

In [78]:
b_np+B_np

array([[[ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5]],

       [[ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5]],

       [[17. , 17. , 17. ],
        [17. , 17. , 17. ],
        [17. , 17. , 17. ]],

       [[ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5]],

       [[ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5]],

       [[ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5]],

       [[ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5]],

       [[ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5]],

       [[ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5]],

       [[ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5]],

       [[ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5]],

       [[ 6.5,  6.5,  6.5],
        [ 6.5,  6.5,  6.5]

In [79]:
%timeit B_np + b_np

2.22 µs ± 56.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [80]:
%timeit B + b

4.72 µs ± 76.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [81]:
# Time of Gauss integration usign pyoti for Array.
%timeit b.gauss_integrate( b )

97.6 ns ± 0.772 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [82]:
# Time of Gauss integration usign pyoti for Array.
%timeit B.gauss_integrate( b )

388 ns ± 2.78 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [83]:
b.gauss_integrate(b)

751.5

In [84]:
4.5*4.5*26+15*15

751.5

In [85]:
# Time  of Gauss integration using Numpy for scalar.
%timeit np.sum(b_np*b_np,axis=0)

5.75 µs ± 52.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [86]:
# Time  of Gauss integration using Numpy for array.
%timeit np.sum(B_np*b_np,axis=0)

8.85 µs ± 166 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [88]:
B.gauss_integrate(b)

array([[264., 264., 264.],
       [264., 264., 264.],
       [264., 264., 264.]])

In [87]:
np.sum(B_np*b_np,axis=0)

array([[264., 264., 264.],
       [264., 264., 264.],
       [264., 264., 264.]])

In [89]:
res = B.copy()
%timeit r.sum(B,B,out=res)

466 ns ± 2.12 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [90]:
%timeit B+B

4.73 µs ± 77.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [91]:
B+B

dmatfe< nip: 27, 
(Integration point - 0) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 1) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 2) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 3) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 4) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 5) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 6) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 7) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 8) 
-------------------------
[[4. 4. 4.]
 [4. 4.

In [92]:
res.set(0)
res

dmatfe< nip: 27, 
(Integration point - 0) 
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------
(Integration point - 1) 
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------
(Integration point - 2) 
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------
(Integration point - 3) 
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------
(Integration point - 4) 
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------
(Integration point - 5) 
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------
(Integration point - 6) 
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------
(Integration point - 7) 
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------
(Integration point - 8) 
-------------------------
[[0. 0. 0.]
 [0. 0.

In [93]:
%timeit r.mul(B,B,out=res)
res

466 ns ± 4.91 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


dmatfe< nip: 27, 
(Integration point - 0) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 1) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 2) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 3) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 4) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 5) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 6) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 7) 
-------------------------
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
-------------------------
(Integration point - 8) 
-------------------------
[[4. 4. 4.]
 [4. 4.

In [94]:

%timeit r.mul(B,b,out=res)
res

418 ns ± 4.25 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


dmatfe< nip: 27, 
(Integration point - 0) 
-------------------------
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
-------------------------
(Integration point - 1) 
-------------------------
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
-------------------------
(Integration point - 2) 
-------------------------
[[30. 30. 30.]
 [30. 30. 30.]
 [30. 30. 30.]]
-------------------------
(Integration point - 3) 
-------------------------
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
-------------------------
(Integration point - 4) 
-------------------------
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
-------------------------
(Integration point - 5) 
-------------------------
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
-------------------------
(Integration point - 6) 
-------------------------
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
-------------------------
(Integration point - 7) 
-------------------------
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
-------------------------
(Integration point - 8) 
-------------------------
[[9. 9. 9.

In [95]:
res_np = B_np.copy()
%timeit np.multiply(B_np,B_np,out=res_np)

831 ns ± 6.35 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [96]:
%timeit B_np*B_np

702 ns ± 5.72 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [101]:
B_spr = spr.csr_matrix((3,3))

In [102]:
type(B_spr) == spr.csr_matrix

True

In [103]:
isinstance(B_spr,spr.spmatrix)

True

4.48 µs ± 22.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
