# Test Dense OTI matrix type.

This tests all implementations regarding the new matrix type for the dense implementation only.

In [3]:
# 1. SET GLOBAL PATH 
import sys
path2oti = '../../build/'
sys.path.append(path2oti) # Add path to OTI library.

# 2. IMPORT LIBRARIES.
# Only dense imported.
from pyoti.dense import *
from pyoti.core import imdir
from pyoti.real import zeros as rzeros
from pyoti.real import ones as rones

## Creation

There are three main creators 

```python
A = zeros(nrows, ncols)
B = ones(nrows, ncols)
I = eye(size)
```

In [4]:
shx = 3
shy = 3

A = zeros(shx,shy)
print(det(A))

0


In [12]:
%timeit det(A)

355 µs ± 4.45 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
B = ones(shx,shy)
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



In [7]:
print(B/2.5)

[[0.4 0.4 0.4]
 [0.4 0.4 0.4]
 [0.4 0.4 0.4]]



In [6]:
%timeit A+B

108 ns ± 0.786 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [17]:
A[7,2] = 8.3

In [18]:
print(A)

[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  3.5 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  8.3 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]]



In [19]:
transpose(A)

omat< ndir: 0, order: 0>
re:
array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 3.5, 0. , 0. , 8.3, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

In [5]:
dot(B,B)

omat< ndir: 0, order: 0>
re:
array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [18]:
# comparison with numpy:
An = np.zeros((shx,shy))
Bn = np.ones((shx,shy))

for i in range(An.shape[0]):
    for j in range(An.shape[1]):
        An[i,j] = ((j+1)*(i+1) )**2
        Bn[i,j] = ((2*i+1)     )**2
    # end for 
# end for 
# %timeit An + Bn

In [19]:
%timeit np.linalg.det(An)

4.87 µs ± 12.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
An*Bn

array([[1.000e+00, 4.000e+00, 9.000e+00],
       [3.600e+01, 1.440e+02, 3.240e+02],
       [2.250e+02, 9.000e+02, 2.025e+03]])

In [22]:
np.linalg.det(An*Bn)

0.0

In [23]:
np.linalg.det(Bn)

0.0

In [24]:
An*Bn

array([[1.000e+00, 4.000e+00, 9.000e+00],
       [3.600e+01, 1.440e+02, 3.240e+02],
       [2.250e+02, 9.000e+02, 2.025e+03]])

In [35]:
A*B

omat< ndir: 5, order: 2>
re:
array([[1.000000e+00, 4.000000e+00, 9.000000e+00, 1.600000e+01,
        2.500000e+01, 3.600000e+01, 4.900000e+01, 6.400000e+01,
        8.100000e+01, 1.000000e+02],
       [3.600000e+01, 1.440000e+02, 3.240000e+02, 5.760000e+02,
        9.000000e+02, 1.296000e+03, 1.764000e+03, 2.304000e+03,
        2.916000e+03, 3.600000e+03],
       [2.250000e+02, 9.000000e+02, 2.025000e+03, 3.600000e+03,
        5.625000e+03, 8.100000e+03, 1.102500e+04, 1.440000e+04,
        1.822500e+04, 2.250000e+04],
       [7.840000e+02, 3.136000e+03, 7.056000e+03, 1.254400e+04,
        1.960000e+04, 2.822400e+04, 3.841600e+04, 5.017600e+04,
        6.350400e+04, 7.840000e+04],
       [2.025000e+03, 8.100000e+03, 1.822500e+04, 3.240000e+04,
        5.062500e+04, 7.290000e+04, 9.922500e+04, 1.296000e+05,
        1.640250e+05, 2.025000e+05],
       [4.356000e+03, 1.742400e+04, 3.920400e+04, 6.969600e+04,
        1.089000e+05, 1.568160e+05, 2.134440e+05, 2.787840e+05,
        3.528360e+

In [32]:
det(A*B)

otinum(1.9807040628566084e+28, ndir: 5, order: 2)

In [9]:
np.dot(Bn,Bn)

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In order to define the matrix with more imaginary directions, the keyword arguments nbases and orders must be set differently in order to 

In [13]:
order  = 2
nbases = 2

A = zeros(shx,shy,nbases=nbases,order=order)
B = ones(shx,shy,nbases=nbases,order=order)

for i in range(An.shape[0]):
    for j in range(An.shape[1]):
        A[i,j] = ((j+1)*(i+1) + (2*i+1)*e(2,nbases=nbases,order=order))**2
        B[i,j] = ((2*i+1)     + (j+1)*e(1,nbases=nbases,order=order)  )**2
    # end for 
# end for 
print("A:")
print(A)


A:
[[ 1.  4.  9.]
 [ 4. 16. 36.]
 [ 9. 36. 81.]]
+ e([1]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([2]) * 
[[ 2.  4.  6.]
 [12. 24. 36.]
 [30. 60. 90.]]
+ e([[1,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([1,2]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([[2,2]]) * 
[[ 1.  1.  1.]
 [ 9.  9.  9.]
 [25. 25. 25.]]



In [14]:
print("B:")
print(B)

B:
[[ 1.  1.  1.]
 [ 9.  9.  9.]
 [25. 25. 25.]]
+ e([1]) * 
[[ 2.  4.  6.]
 [ 6. 12. 18.]
 [10. 20. 30.]]
+ e([2]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([[1,2]]) * 
[[1. 4. 9.]
 [1. 4. 9.]
 [1. 4. 9.]]
+ e([1,2]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([[2,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [25]:
print(A)
print(An)

[[ 1.  4.  9.]
 [ 4. 16. 36.]
 [ 9. 36. 81.]]
+ e([1]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([2]) * 
[[ 2.  4.  6.]
 [12. 24. 36.]
 [30. 60. 90.]]
+ e([[1,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([1,2]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([[2,2]]) * 
[[ 1.  1.  1.]
 [ 9.  9.  9.]
 [25. 25. 25.]]

[[ 1.  4.  9.]
 [ 4. 16. 36.]
 [ 9. 36. 81.]]


In [31]:
print((det(A*B)))

0 + 0 * e([1]) + 0 * e([2]) + 0 * e([[1,2]]) - 17280 * e([1,2]) + 0 * e([[2,2]])


In [44]:
np.linalg.det(An*Bn)
def determinant(M):
    
    res = 0.0
    # add parts:
    for j in range(M.shape[0]):
        
        tmp=1.0
        
        for i in range(M.shape[0]):
            
            print(i,',',(j+i)%M.shape[1],",",M[i,(j+i)%M.shape[1]])
            
            tmp*=M[i,(j+i)%M.shape[1]]
        
        res += tmp
        
    # subtract parts:
    print()
    for j in range(M.shape[0]):
        
        tmp=1.0
        
        for i in range(M.shape[0]):
            
            print(i,',',(M.shape[1]-2-j-i)%M.shape[1],",",M[i,(M.shape[1]-2-j-i)%M.shape[1]] )
            
            tmp *= M[i,(M.shape[1]-2-j-i)%M.shape[1]]
        
        res -= tmp
    return res

In [45]:
An

array([[ 1.,  4.,  9.],
       [ 4., 16., 36.],
       [ 9., 36., 81.]])

In [49]:
print(determinant(A*B))

0 , 0 , 1 + 2 * e([1]) + 2 * e([2]) + 1 * e([[1,2]]) + 4 * e([1,2]) + 1 * e([[2,2]])
1 , 1 , 144 + 192 * e([1]) + 216 * e([2]) + 64 * e([[1,2]]) + 288 * e([1,2]) + 81 * e([[2,2]])
2 , 2 , 2025 + 2430 * e([1]) + 2250 * e([2]) + 729 * e([[1,2]]) + 2700 * e([1,2]) + 625 * e([[2,2]])
0 , 1 , 4 + 16 * e([1]) + 4 * e([2]) + 16 * e([[1,2]]) + 16 * e([1,2]) + 1 * e([[2,2]])
1 , 2 , 324 + 648 * e([1]) + 324 * e([2]) + 324 * e([[1,2]]) + 648 * e([1,2]) + 81 * e([[2,2]])
2 , 0 , 225 + 90 * e([1]) + 750 * e([2]) + 9 * e([[1,2]]) + 300 * e([1,2]) + 625 * e([[2,2]])
0 , 2 , 9 + 54 * e([1]) + 6 * e([2]) + 81 * e([[1,2]]) + 36 * e([1,2]) + 1 * e([[2,2]])
1 , 0 , 36 + 24 * e([1]) + 108 * e([2]) + 4 * e([[1,2]]) + 72 * e([1,2]) + 81 * e([[2,2]])
2 , 1 , 900 + 720 * e([1]) + 1500 * e([2]) + 144 * e([[1,2]]) + 1200 * e([1,2]) + 625 * e([[2,2]])

0 , 1 , 4 + 16 * e([1]) + 4 * e([2]) + 16 * e([[1,2]]) + 16 * e([1,2]) + 1 * e([[2,2]])
1 , 0 , 36 + 24 * e([1]) + 108 * e([2]) + 4 * e([[1,2]]) + 72 * e([1,2]) +

In [35]:
1*16*81+4*36*9+9*4*36


3888

In [35]:
print('A*B')
C = A*B
print(C)

A*B
[[1.000000e+00 4.000000e+00 9.000000e+00 1.600000e+01 2.500000e+01
  3.600000e+01 4.900000e+01 6.400000e+01 8.100000e+01 1.000000e+02]
 [3.600000e+01 1.440000e+02 3.240000e+02 5.760000e+02 9.000000e+02
  1.296000e+03 1.764000e+03 2.304000e+03 2.916000e+03 3.600000e+03]
 [2.250000e+02 9.000000e+02 2.025000e+03 3.600000e+03 5.625000e+03
  8.100000e+03 1.102500e+04 1.440000e+04 1.822500e+04 2.250000e+04]
 [7.840000e+02 3.136000e+03 7.056000e+03 1.254400e+04 1.960000e+04
  2.822400e+04 3.841600e+04 5.017600e+04 6.350400e+04 7.840000e+04]
 [2.025000e+03 8.100000e+03 1.822500e+04 3.240000e+04 5.062500e+04
  7.290000e+04 9.922500e+04 1.296000e+05 1.640250e+05 2.025000e+05]
 [4.356000e+03 1.742400e+04 3.920400e+04 6.969600e+04 1.089000e+05
  1.568160e+05 2.134440e+05 2.787840e+05 3.528360e+05 4.356000e+05]
 [8.281000e+03 3.312400e+04 7.452900e+04 1.324960e+05 2.070250e+05
  2.981160e+05 4.057690e+05 5.299840e+05 6.707610e+05 8.281000e+05]
 [1.440000e+04 5.760000e+04 1.296000e+05 2.304000e+

In [36]:
%timeit A*B

2.03 µs ± 20.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
# Using numpy array typed object to support array ops:
An = np.empty((shx,shy),dtype=object)
Bn = np.empty((shx,shy),dtype=object)

for i in range(An.shape[0]):
    for j in range(An.shape[1]):
        An[i,j] = ((j+1)*(i+1)+ (2*i+1)*e(2,nbases=nbases,order=order))**2
        Bn[i,j] = ((2*i+1)      + (j+1)*e(1,nbases=nbases,order=order))**2
    # end for 
# end for 

In [31]:
print(Bn)

[[otinum(1.0, ndir: 5, order: 2) otinum(1.0, ndir: 5, order: 2)
  otinum(1.0, ndir: 5, order: 2) otinum(1.0, ndir: 5, order: 2)
  otinum(1.0, ndir: 5, order: 2) otinum(1.0, ndir: 5, order: 2)
  otinum(1.0, ndir: 5, order: 2) otinum(1.0, ndir: 5, order: 2)
  otinum(1.0, ndir: 5, order: 2) otinum(1.0, ndir: 5, order: 2)]
 [otinum(9.0, ndir: 5, order: 2) otinum(9.0, ndir: 5, order: 2)
  otinum(9.0, ndir: 5, order: 2) otinum(9.0, ndir: 5, order: 2)
  otinum(9.0, ndir: 5, order: 2) otinum(9.0, ndir: 5, order: 2)
  otinum(9.0, ndir: 5, order: 2) otinum(9.0, ndir: 5, order: 2)
  otinum(9.0, ndir: 5, order: 2) otinum(9.0, ndir: 5, order: 2)]
 [otinum(25.0, ndir: 5, order: 2) otinum(25.0, ndir: 5, order: 2)
  otinum(25.0, ndir: 5, order: 2) otinum(25.0, ndir: 5, order: 2)
  otinum(25.0, ndir: 5, order: 2) otinum(25.0, ndir: 5, order: 2)
  otinum(25.0, ndir: 5, order: 2) otinum(25.0, ndir: 5, order: 2)
  otinum(25.0, ndir: 5, order: 2) otinum(25.0, ndir: 5, order: 2)]
 [otinum(49.0, ndir: 5, ord

In [38]:
%timeit An*Bn

63.7 µs ± 524 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [39]:
Cn = An*Bn
# print(Cn)
print(Cn[5,5])

156816 + 171072 * e([1]) + 95832 * e([2]) + 46656 * e([[1,2]]) + 104544 * e([1,2]) + 14641 * e([[2,2]])


In [41]:
C = A*B
print(C[5,5])

156816 + 171072 * e([1]) + 95832 * e([2]) + 46656 * e([[1,2]]) + 104544 * e([1,2]) + 14641 * e([[2,2]])


In [47]:
Dn = np.dot(An,Bn)
print(Dn[6,3])

4.39123e+06 + 2.22068e+06 * e([1]) + 1.93193e+06 * e([2]) + 301840 * e([[1,2]]) + 1.04104e+06 * e([1,2]) + 224770 * e([[2,2]])


In [48]:
D = dot(A,B)
print(D[6,3])

4.39123e+06 + 2.22068e+06 * e([1]) + 1.93193e+06 * e([2]) + 301840 * e([[1,2]]) + 1.04104e+06 * e([1,2]) + 224770 * e([[2,2]])


In [44]:
%timeit dot(A,B)

10.7 µs ± 127 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [45]:
%timeit np.dot(An,Bn)

1.04 ms ± 31.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [46]:
print(D)

[[  89617.   89617.   89617.   89617.   89617.   89617.   89617.   89617.
    89617.   89617.]
 [ 358468.  358468.  358468.  358468.  358468.  358468.  358468.  358468.
   358468.  358468.]
 [ 806553.  806553.  806553.  806553.  806553.  806553.  806553.  806553.
   806553.  806553.]
 [1433872. 1433872. 1433872. 1433872. 1433872. 1433872. 1433872. 1433872.
  1433872. 1433872.]
 [2240425. 2240425. 2240425. 2240425. 2240425. 2240425. 2240425. 2240425.
  2240425. 2240425.]
 [3226212. 3226212. 3226212. 3226212. 3226212. 3226212. 3226212. 3226212.
  3226212. 3226212.]
 [4391233. 4391233. 4391233. 4391233. 4391233. 4391233. 4391233. 4391233.
  4391233. 4391233.]
 [5735488. 5735488. 5735488. 5735488. 5735488. 5735488. 5735488. 5735488.
  5735488. 5735488.]
 [7258977. 7258977. 7258977. 7258977. 7258977. 7258977. 7258977. 7258977.
  7258977. 7258977.]
 [8961700. 8961700. 8961700. 8961700. 8961700. 8961700. 8961700. 8961700.
  8961700. 8961700.]]
+ e([1]) * 
[[   11330.    22660.    33990.    45

In [ ]:
B = B+e(2, nbases=nbases, order=order)*3 

In [ ]:
print(B/3)

In [ ]:
print(3*B)

In [ ]:
print(B*3.5)

In [ ]:
C = 2.5*rones(shx,shy)
print(C)

In [ ]:
print(B*C)

In [ ]:
print(C*B)

In [ ]:
print(B/C)

In [ ]:
3/2.5

In [ ]:
print(B*B*3)

In [ ]:
%timeit B*B

In [ ]:
b = 1.0+3*e(2,nbases=nbases,order=order)

In [ ]:
print(b)

In [ ]:
%timeit b*B

In [ ]:
print(b*B)