# Test Dense OTI matrix type.

This tests all implementations regarding the new matrix type for the dense implementation only.

In [1]:
# 1. SET GLOBAL PATH 
import sys
path2oti = '../../build/'
sys.path.append(path2oti) # Add path to OTI library.

# 2. IMPORT LIBRARIES.
# Only dense imported.
from pyoti.dense import *
from pyoti.core import imdir
from pyoti.real import zeros as rzeros
from pyoti.real import ones as rones

## Creation

There are three main creators 

```python
A = zeros(nrows, ncols)
B = ones(nrows, ncols)
I = eye(size)
```

In [2]:
shx = 10
shy = 10

A = zeros(shx,shy)
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]



In [3]:
B = ones(shx,shy)
print(B)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]



In [4]:
print(B/2.5)

[[0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
 [0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
 [0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
 [0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
 [0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
 [0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
 [0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
 [0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
 [0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
 [0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]]



In [5]:
%timeit A+B

299 ns ± 4.88 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
# comparison with numpy:
An = np.zeros((shx,shy))
Bn = np.ones((shx,shy))

%timeit An + Bn

618 ns ± 17.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In order to define the matrix with more imaginary directions, the keyword arguments nbases and orders must be set differently in order to 

In [7]:
order  = 2
nbases = 2

A = zeros(shx,shy,nbases=nbases,order=order)
B = ones(shx,shy,nbases=nbases,order=order)
A

omat< ndir: 5, order: 2>
re:
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
%timeit A+B

In [8]:
# Using numpy array typed object to support array ops:
An = np.empty((shx,shy),dtype=object)
Bn = np.empty((shx,shy),dtype=object)

for i in range(An.shape[0]):
    for j in range(An.shape[1]):
        An[i,j] = 0*e(1,nbases=nbases,order=order)
        Bn[i,j] = 1.0+3*e(1,nbases=nbases,order=order)
    # end for 
# end for 

In [ ]:
%timeit Bn * Bn

In [ ]:
A + B

In [9]:
B = B+e(2, nbases=nbases, order=order)*3 

In [ ]:
print(B/3)

In [ ]:
print(3*B)

In [ ]:
print(B*3.5)

In [ ]:
C = 2.5*rones(shx,shy)
print(C)

In [ ]:
print(B*C)

In [ ]:
print(C*B)

In [ ]:
print(B/C)

In [ ]:
3/2.5

In [ ]:
print(B)

In [ ]:
%timeit B*B

In [14]:
b = 1.0+3*e(2,nbases=nbases,order=order)

In [15]:
print(b)

1 + 0 * e([1]) + 3 * e([2]) + 0 * e([[1,2]]) + 0 * e([1,2]) + 0 * e([[2,2]])


In [18]:
%timeit b*B

2.27 µs ± 35.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
print(b*B)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
+ e([1]) * 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
+ e([2]) * 
[[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 