In [1]:
import numpy as np


In [4]:
fulldir_n1m10 = np.load("../../build/data/v1.0/fulldir_n1_m10.npy")
fulldir_n1m10

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=uint16)

In [5]:
fulldir_n2m10 = np.load("../../build/data/v1.0/fulldir_n2_m10.npy")
fulldir_n2m10

array([[ 1,  1],
       [ 1,  2],
       [ 2,  2],
       [ 1,  3],
       [ 2,  3],
       [ 3,  3],
       [ 1,  4],
       [ 2,  4],
       [ 3,  4],
       [ 4,  4],
       [ 1,  5],
       [ 2,  5],
       [ 3,  5],
       [ 4,  5],
       [ 5,  5],
       [ 1,  6],
       [ 2,  6],
       [ 3,  6],
       [ 4,  6],
       [ 5,  6],
       [ 6,  6],
       [ 1,  7],
       [ 2,  7],
       [ 3,  7],
       [ 4,  7],
       [ 5,  7],
       [ 6,  7],
       [ 7,  7],
       [ 1,  8],
       [ 2,  8],
       [ 3,  8],
       [ 4,  8],
       [ 5,  8],
       [ 6,  8],
       [ 7,  8],
       [ 8,  8],
       [ 1,  9],
       [ 2,  9],
       [ 3,  9],
       [ 4,  9],
       [ 5,  9],
       [ 6,  9],
       [ 7,  9],
       [ 8,  9],
       [ 9,  9],
       [ 1, 10],
       [ 2, 10],
       [ 3, 10],
       [ 4, 10],
       [ 5, 10],
       [ 6, 10],
       [ 7, 10],
       [ 8, 10],
       [ 9, 10],
       [10, 10]], dtype=uint16)

In [16]:
multtabl_n4m10_0 = np.load("../../build/data/v1.0/multtabl_n4_m10_0.npy")
multtabl_n4m10_0

array([[  0,   1,   2, ..., 688, 696, 705],
       [  1,   2,   3, ..., 689, 697, 706],
       [  5,   6,   7, ..., 690, 698, 707],
       ...,
       [210, 211, 212, ..., 695, 703, 712],
       [330, 331, 332, ..., 703, 704, 713],
       [495, 496, 497, ..., 712, 713, 714]], dtype=uint64)

In [13]:
ndirs_n2m10 = np.load("../../build/data/v1.0/ndirs_n2_m10.npy")
ndirs_n2m10

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=uint64)

In [9]:
ndirs_n3m10 = np.load("../../build/data/v1.0/ndirs_n3_m10.npy")
ndirs_n3m10

array([  0,   1,   4,  10,  20,  35,  56,  84, 120, 165, 220],
      dtype=uint64)

In [8]:
from scipy.special import comb 
n=3
m=10
comb(n+m-1,m-1)

220.0