# How to use dual matrices with ```spr_duallib```
# V 0.1
``` python
""" 
Contributors to this file:
Mauricio Aristizabal Cano

Date of creation:  25 04 2016
Last modification: 04 05 2016
Universidad EAFIT, Medellin, Colombia.
"""
```

## 0. Introduction
This file will help to understand how to use sparse matrices with dual numbers, implemented with the library ```spr_duallib```. This will require as basic knowledge, how the ```spr_dualnum``` class works.  The library is based o the CSR sparse matrix format.

## 1. Getting started

First, import the library as follows (we will also import numpy because it is necesary to handle several operations).

In [1]:
import spr_duallib as dn
import numpy as np
np.set_printoptions(precision=2,linewidth=240,suppress=True)

A very short explanation how th CSR format works: 
Let's consider the matrix
$$
\begin{bmatrix}
1 & 0 & 2 & 0\\
0 & 3 & 0 & 0\\
0 & 0 & 0 & 0\\
0 & 4 & 5 & 0\\
\end{bmatrix}
$$

The idea of a sparse matrix is to store only the non-zero values of the matrix. It is then formed (mainly) by three attributes: 
- ```data```: Array of the non-zero values, for the example $[1,2,3,4,5]$
- ```index```: Array that indicates for each element in ```data``` to what column it belongs to, for this example the array is $[0,2,1,1,2]$
- ``` indxptr```: An array of values that indicates for row ```i```, the data associated is  ```data[indxptr[i]:indxptr[i+1]``` and the column values are: ```index[indxptr[i]:indxptr[i+1]```. For the matrix example, $[0,2,3,3,5]$.

## 1.1 Create a matrix

There are 4 manners to create a sparse matrix object:


### 1.1.1 Direct CSR format
The creation of a sparse matrix is done by simply placing the ```data```, ```index``` and ```indxptr``` arrays. In this case a ```spr_dualmat``` can be created using the constructor 

```spr_dualmat((data, index, indxptr), [shape=(M, N), maxorder = k])```

in which ```shape``` determines the shape of the matrix. If it is not present, then the shape will be automatically deduced from index and indxptr. 
Also, ```maxorder``` determines the maximum order of the internal elements. If it is not present, maxorder will use the maximum of the orders of the 

Using the previous example, the resulting matrix is  


In [2]:
data = [1,2,3,4,5]
index = [0,2,1,1,2]
indxptr = [0,2,3,3,5]

a = dn.spr_dualmat((data, index, indxptr),shape = (4,4))

Now, how do we know what have we done? We need to display what we have created. There are two ways. In one method, we can use the representation method, in which we will only get the general characteristics of the matrix, i.e. shape, number of elements and maxorder. We won't get any other information.

In [3]:
a

<(4, 4) sparse matrix with 5 spr_dualnum elements of order 1>

The second method is to use the ```print``` command. This will print allways the constructor in the direct CSR format, using ```spr_dualnum``` objects:

In [4]:
print(a)

spr_dualmat(([spr_dualnum([0],[1.],1),spr_dualnum([0],[2.],1),spr_dualnum([0],[3.],1),spr_dualnum([0],[4.],1),spr_dualnum([0],[5.],1)], [0,2,1,1,2], [0,2,3,3,5]), shape=(4,4), maxorder=1)


A more human friendly way to use the method is to create an a full matrix, including the zero elements, this is, a dense representation of the matrix. This is done using ```toarray()``` method. In this case, the visualization becomes as follows (Recall zero in ```spr_dualnum``` is ```spr_dualnum([], [], 1)```).

In [5]:
a.toarray()

array([[spr_dualnum([0], [1.], 1), spr_dualnum([], [], 1), spr_dualnum([0], [2.], 1), spr_dualnum([], [], 1)],
       [spr_dualnum([], [], 1), spr_dualnum([0], [3.], 1), spr_dualnum([], [], 1), spr_dualnum([], [], 1)],
       [spr_dualnum([], [], 1), spr_dualnum([], [], 1), spr_dualnum([], [], 1), spr_dualnum([], [], 1)],
       [spr_dualnum([], [], 1), spr_dualnum([0], [4.], 1), spr_dualnum([0], [5.], 1), spr_dualnum([], [], 1)]], dtype=object)

We see that indeed we have created the example matrix. In order to check the attributes of the matrix, we can call them by

In [6]:
a.data

array([spr_dualnum([0], [1.], 1), spr_dualnum([0], [2.], 1), spr_dualnum([0], [3.], 1), spr_dualnum([0], [4.], 1), spr_dualnum([0], [5.], 1)], dtype=object)

In [7]:
a.index

[0, 2, 1, 1, 2]

In [8]:
a.indxptr

array([0, 2, 3, 3, 5])

There is another attribute which is the maxorder attribute, which sets the maximum order for all data in the matrix.

In [9]:
a.maxorder

1

###1.1.2 Empty matrix
To create an empty matrix one can simply call the matrix constructor with the shape of the matrix, as follows

In [10]:
a=dn.spr_dualmat((3,4))

In order to get the representation of the matrix, it has a representation mode, which returns the shape of the matrix with the number of non-zero elements and the order (of the ```spr_dualnum```s it will hold)

In [11]:
a

<(3, 4) sparse matrix with 0 spr_dualnum elements of order 1>

In [12]:
print(a)

spr_dualmat(([], [], [0,0,0,0]), shape=(3,4), maxorder=1)


### 1.1.3 Dense constructor

Given a dense matrix, either with real number of with dual numbers, the library creates a sparse matrix. Hence

In [13]:
dense = np.array([[1,0,2,0],
                  [0,3,0,0],
                  [0,0,0,0],
                  [0,4,5,0]
                 ])

a= dn.spr_dualmat(dense)
a

<(4, 4) sparse matrix with 5 spr_dualnum elements of order 1>

In [14]:
a.toarray()

array([[spr_dualnum([0], [1.], 1), spr_dualnum([], [], 1), spr_dualnum([0], [2.], 1), spr_dualnum([], [], 1)],
       [spr_dualnum([], [], 1), spr_dualnum([0], [3.], 1), spr_dualnum([], [], 1), spr_dualnum([], [], 1)],
       [spr_dualnum([], [], 1), spr_dualnum([], [], 1), spr_dualnum([], [], 1), spr_dualnum([], [], 1)],
       [spr_dualnum([], [], 1), spr_dualnum([0], [4.], 1), spr_dualnum([0], [5.], 1), spr_dualnum([], [], 1)]], dtype=object)

In [15]:
a.data

array([spr_dualnum([0], [1.], 1), spr_dualnum([0], [2.], 1), spr_dualnum([0], [3.], 1), spr_dualnum([0], [4.], 1), spr_dualnum([0], [5.], 1)], dtype=object)

In [16]:
a.index

[0, 2, 1, 1, 2]

In [17]:
a.indxptr

array([0, 2, 3, 3, 5])

In [18]:
a.maxorder

1

###1.1.4 Using individually specifyed data

The last form to create a sparse matrix is to specify each element with its corresponding position, this is, 

```a=spr_dualmat((data, (row_ind, col_ind)), [shape=(M, N), maxorder=k])```,

where ```a[row_ind[j],col_ind[j]]=data[k]```

All the input variables should be aligned as stated above, but they don't have to be ordered. If shape is not given, the shape will be derived from the ```col_ind``` and ```row_ind```.

For the previous example, it becomes as follows:

In [19]:
data = [5,2,3,1,4]
col_ind = [2,2,1,0,1]
row_ind = [3,0,1,0,3]


a=dn.spr_dualmat((data, (row_ind, col_ind)),shape=(4,4))
a

<(4, 4) sparse matrix with 5 spr_dualnum elements of order 1>

In [20]:
print(a)

spr_dualmat(([spr_dualnum([0],[1.],1),spr_dualnum([0],[2.],1),spr_dualnum([0],[3.],1),spr_dualnum([0],[4.],1),spr_dualnum([0],[5.],1)], [0,2,1,1,2], [0,2,3,3,5]), shape=(4,4), maxorder=1)


In [21]:
a.toarray()

array([[spr_dualnum([0], [1.], 1), spr_dualnum([], [], 1), spr_dualnum([0], [2.], 1), spr_dualnum([], [], 1)],
       [spr_dualnum([], [], 1), spr_dualnum([0], [3.], 1), spr_dualnum([], [], 1), spr_dualnum([], [], 1)],
       [spr_dualnum([], [], 1), spr_dualnum([], [], 1), spr_dualnum([], [], 1), spr_dualnum([], [], 1)],
       [spr_dualnum([], [], 1), spr_dualnum([0], [4.], 1), spr_dualnum([0], [5.], 1), spr_dualnum([], [], 1)]], dtype=object)

In [22]:
a.maxorder

1

Its attributes remain the same as before.

## 1.2 Operations
### 1.2.1 Sum
Sum can be operated with 4 different types of data: real numbers, sparse dual numbers, sparse and dense matrix. Have in mind that this operation preserves the maximum between the order of the matrix and the order of whatever comes to be operated.

Therefore, the 4 cases give:

- **Sum to real number**

In [23]:
print(a+5)

spr_dualmat(([spr_dualnum([0],[6.],1),spr_dualnum([0],[7.],1),spr_dualnum([0],[8.],1),spr_dualnum([0],[9.],1),spr_dualnum([0],[10.],1)], [0,2,1,1,2], [0,2,3,3,5]), shape=(4,4), maxorder=1)


All terms were summed by real number 5.

- **Sum to sparse hyper-dual number:**

In [24]:
print(a+30.0*dn.e([1,2]))

spr_dualmat(([spr_dualnum([0,5],[1.,30.],2),spr_dualnum([0,5],[2.,30.],2),spr_dualnum([0,5],[3.,30.],2),spr_dualnum([0,5],[4.,30.],2),spr_dualnum([0,5],[5.,30.],2)], [0,2,1,1,2], [0,2,3,3,5]), shape=(4,4), maxorder=2)


This results in all terms added by $30 \ \epsilon_1\epsilon_2$, with all changed to order 2.

- **Sum to other sparse matrix**

In [25]:
dense_b = np.array([[1,0,2,1],
                  [0,3,0,0],
                  [0,0,3,0],
                  [0,4,5,0]
                 ])*dn.e([1,2,3])

# define new matrix
b = dn.spr_dualmat(dense_b)
print(b)

spr_dualmat(([spr_dualnum([73],[1.],3),spr_dualnum([73],[2.],3),spr_dualnum([73],[1.],3),spr_dualnum([73],[3.],3),spr_dualnum([73],[3.],3),spr_dualnum([73],[4.],3),spr_dualnum([73],[5.],3)], [0,2,3,1,2,1,2], [0,3,4,5,7]), shape=(4,4), maxorder=3)


In [26]:
print(a+b)

spr_dualmat(([spr_dualnum([0,73],[1.,1.],3),spr_dualnum([0,73],[2.,2.],3),spr_dualnum([73],[1.],3),spr_dualnum([0,73],[3.,3.],3),spr_dualnum([73],[3.],3),spr_dualnum([0,73],[4.,4.],3),spr_dualnum([0,73],[5.,5.],3)], [0,2,3,1,2,1,2], [0,3,4,5,7]), shape=(4,4), maxorder=3)


The result shows that new positions are made, and those positions that share values are summed.

- **Sum with a dense matrix**

In [27]:
print(a+dense_b)

spr_dualmat(([spr_dualnum([0,73],[1.,1.],3),spr_dualnum([0,73],[2.,2.],3),spr_dualnum([73],[1.],3),spr_dualnum([0,73],[3.,3.],3),spr_dualnum([73],[3.],3),spr_dualnum([0,73],[4.,4.],3),spr_dualnum([0,73],[5.,5.],3)], [0,2,3,1,2,1,2], [0,3,4,5,7]), shape=(4,4), maxorder=3)


The result is the same as before.

Addition also works as inplace:

In [28]:
b+=a

In [29]:
print(b)

spr_dualmat(([spr_dualnum([0,73],[1.,1.],3),spr_dualnum([0,73],[2.,2.],3),spr_dualnum([73],[1.],3),spr_dualnum([0,73],[3.,3.],3),spr_dualnum([73],[3.],3),spr_dualnum([0,73],[4.,4.],3),spr_dualnum([0,73],[5.,5.],3)], [0,2,3,1,2,1,2], [0,3,4,5,7]), shape=(4,4), maxorder=3)


### 1.2.2 Multiplication

Multiplication can be performed either elementwise or dot multiplication. the first one is performed using the operator ```*```. In this sense, the matrix can be multiplyed by a real number, a ```spr_dualnum``` or a same shape matrix (dense or sparse). Examples of this are shown below: 

In [30]:
print(a*3)

spr_dualmat(([spr_dualnum([0],[3.],1),spr_dualnum([0],[6.],1),spr_dualnum([0],[9.],1),spr_dualnum([0],[12.],1),spr_dualnum([0],[15.],1)], [0,2,1,1,2], [0,2,3,3,5]), shape=(4,4), maxorder=1)


In [31]:
print(a*dn.e([1]))

spr_dualmat(([spr_dualnum([1],[1.],1),spr_dualnum([1],[2.],1),spr_dualnum([1],[3.],1),spr_dualnum([1],[4.],1),spr_dualnum([1],[5.],1)], [0,2,1,1,2], [0,2,3,3,5]), shape=(4,4), maxorder=1)


In [32]:
print(a*dn.e([1,2,3])) # Only the minimum order is preserved.

spr_dualmat(([], [], [0,0,0,0,0]), shape=(4,4), maxorder=1)


In [33]:
a.changeOrder(3)
print((a*b).toarray())

[[spr_dualnum([0,73], [1.,1.], 3) spr_dualnum([], [], 3) spr_dualnum([0,73], [4.,4.], 3) spr_dualnum([], [], 3)]
 [spr_dualnum([], [], 3) spr_dualnum([0,73], [9.,9.], 3) spr_dualnum([], [], 3) spr_dualnum([], [], 3)]
 [spr_dualnum([], [], 3) spr_dualnum([], [], 3) spr_dualnum([], [], 3) spr_dualnum([], [], 3)]
 [spr_dualnum([], [], 3) spr_dualnum([0,73], [16.,16.], 3) spr_dualnum([0,73], [25.,25.], 3) spr_dualnum([], [], 3)]]


In [34]:
(b*a).toarray()

array([[spr_dualnum([0,73], [1.,1.], 3), spr_dualnum([], [], 3), spr_dualnum([0,73], [4.,4.], 3), spr_dualnum([], [], 3)],
       [spr_dualnum([], [], 3), spr_dualnum([0,73], [9.,9.], 3), spr_dualnum([], [], 3), spr_dualnum([], [], 3)],
       [spr_dualnum([], [], 3), spr_dualnum([], [], 3), spr_dualnum([], [], 3), spr_dualnum([], [], 3)],
       [spr_dualnum([], [], 3), spr_dualnum([0,73], [16.,16.], 3), spr_dualnum([0,73], [25.,25.], 3), spr_dualnum([], [], 3)]], dtype=object)

In [35]:
b*=a
b.toarray()

array([[spr_dualnum([0,73], [1.,1.], 3), spr_dualnum([], [], 3), spr_dualnum([0,73], [4.,4.], 3), spr_dualnum([], [], 3)],
       [spr_dualnum([], [], 3), spr_dualnum([0,73], [9.,9.], 3), spr_dualnum([], [], 3), spr_dualnum([], [], 3)],
       [spr_dualnum([], [], 3), spr_dualnum([], [], 3), spr_dualnum([], [], 3), spr_dualnum([], [], 3)],
       [spr_dualnum([], [], 3), spr_dualnum([0,73], [16.,16.], 3), spr_dualnum([0,73], [25.,25.], 3), spr_dualnum([], [], 3)]], dtype=object)

As seen, all mltiplication is defined fully operational in the library.

The dot product is called using ```dn.dot(a,b)```, under the normal inner product contition (for matrices) that inner dimensions must be the same. For this case:

In [36]:
dense1 = np.array([[1,2,4],
                  [5,6,8],
                  [0,7,0],
                  [0,0,1]
                 ])

dense2 = np.array([[1,2,3,0],
                   [5,6,0,8],
                   [5,0,9,0],
                 ])

In [37]:
dot_prod= np.dot(dense1,dense2)
print(dot_prod)

[[31 14 39 16]
 [75 46 87 48]
 [35 42  0 56]
 [ 5  0  9  0]]


In [38]:
a = dn.spr_dualmat(dense1)
b = dn.spr_dualmat(dense2)

print((dn.dot(a,b)).toarray())

[[spr_dualnum([0], [31.], 1) spr_dualnum([0], [14.], 1) spr_dualnum([0], [39.], 1) spr_dualnum([0], [16.], 1)]
 [spr_dualnum([0], [75.], 1) spr_dualnum([0], [46.], 1) spr_dualnum([0], [87.], 1) spr_dualnum([0], [48.], 1)]
 [spr_dualnum([0], [35.], 1) spr_dualnum([0], [42.], 1) spr_dualnum([], [], 1) spr_dualnum([0], [56.], 1)]
 [spr_dualnum([0], [5.], 1) spr_dualnum([], [], 1) spr_dualnum([0], [9.], 1) spr_dualnum([], [], 1)]]


In [41]:
# Test solve methdo

Adense = np.array([[3,2,9],
                  [1,1,1],
                  [7,5,3]
                 ])

A = dn.spr_dualmat(Adense)

b = np.array([34,6,26])

x = dn.solve(A,b)

In [42]:
print(x)

[spr_dualnum([0], [1.], 1) spr_dualnum([0], [2.], 1) spr_dualnum([0], [3.], 1)]


In [43]:
# Test solve methdo

Adense = np.array([[-1.,  4., -3.,  6., -2.],
                [ 3., -5., -2.,  7.,  4.],
                [ 1.,  2.,  5., -5., -3.],
                [-5.,  1., -4.,  8.,  5.],
                [ 2., -1.,  1.,  9., -2.]
                  ])


A = dn.spr_dualmat(Adense)

b = np.array([-26., 51.,-25.,10., -1.])

x = dn.solve(A,b)

[[-1.  4. -3.  6. -2.]
 [ 3. -5. -2.  7.  4.]
 [ 1.  2.  5. -5. -3.]
 [-5.  1. -4.  8.  5.]
 [ 2. -1.  1.  9. -2.]]


In [44]:
print(x)

[spr_dualnum([0], [3.], 1) spr_dualnum([0], [-4.], 1) spr_dualnum([0], [-1.], 1) spr_dualnum([], [], 1) spr_dualnum([0], [5.], 1)]


In [46]:
s=dn.identity(3,maxorder=4)
s.toarray()

array([[spr_dualnum([0], [1.], 4), spr_dualnum([], [], 4), spr_dualnum([], [], 4)],
       [spr_dualnum([], [], 4), spr_dualnum([0], [1.], 4), spr_dualnum([], [], 4)],
       [spr_dualnum([], [], 4), spr_dualnum([], [], 4), spr_dualnum([0], [1.], 4)]], dtype=object)