# Test Dense OTI matrix type.

This tests all implementations regarding the new matrix type for the dense implementation only.

In [1]:
# 1. SET GLOBAL PATH 
import sys
path2oti = '../../build/'
sys.path.append(path2oti) # Add path to OTI library.

# 2. IMPORT LIBRARIES.
# Only dense imported.
from pyoti.dense import *
from pyoti.real import zeros as rzeros
from pyoti.real import ones as rones

## Creation

There are three main creators 

```python
A = zeros(nrows, ncols)
B = ones(nrows, ncols)
I = eye(size)
```

In [2]:
shx = 4
shy = 3

A = zeros(shx,shy)
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [3]:
B = ones(shx,shy)
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



In [4]:
print(B/2.5)

[[0.4 0.4 0.4]
 [0.4 0.4 0.4]
 [0.4 0.4 0.4]
 [0.4 0.4 0.4]]



In [5]:
%timeit A+B

109 ns ± 0.279 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [ ]:
# comparison with numpy:
An = np.zeros((shx,shy))
Bn = np.ones((shx,shy))

%timeit An + Bn

In order to define the matrix with more imaginary directions, the keyword arguments nbases and orders must be set differently in order to 

In [8]:
order  = 2
nbases = 2

A = zeros(shx,shy,nbases=nbases,order=order)
B = ones(shx,shy,nbases=nbases,order=order)
A

omat< ndir: 5, order: 2>
re:
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
%timeit A+B

312 ns ± 2.31 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
# Using numpy array typed object to support array ops:
An = np.empty((shx,shy),dtype=object)
Bn = np.empty((shx,shy),dtype=object)

for i in range(An.shape[0]):
    for j in range(An.shape[1]):
        An[i,j] = 0*e(1,nbases=nbases,order=order)
        Bn[i,j] = 1.0+0*e(1,nbases=nbases,order=order)
    # end for 
# end for 

In [11]:
%timeit An + Bn

2.88 µs ± 26 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
A + B

omat< ndir: 5, order: 2>
re:
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
Bn*3

array([[otinum(3.0, ndir: 5, order: 2), otinum(3.0, ndir: 5, order: 2),
        otinum(3.0, ndir: 5, order: 2)],
       [otinum(3.0, ndir: 5, order: 2), otinum(3.0, ndir: 5, order: 2),
        otinum(3.0, ndir: 5, order: 2)],
       [otinum(3.0, ndir: 5, order: 2), otinum(3.0, ndir: 5, order: 2),
        otinum(3.0, ndir: 5, order: 2)],
       [otinum(3.0, ndir: 5, order: 2), otinum(3.0, ndir: 5, order: 2),
        otinum(3.0, ndir: 5, order: 2)]], dtype=object)

In [14]:
B = B+e(2, nbases=nbases, order=order)*3 

In [16]:
print(B/3)

[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
+ e([1]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([2]) * 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
+ e([[1,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([1,2]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([[2,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [17]:
print(3*B)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
+ e([1]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([2]) * 
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
+ e([[1,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([1,2]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([[2,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [18]:
print(B*3.5)

[[3.5 3.5 3.5]
 [3.5 3.5 3.5]
 [3.5 3.5 3.5]
 [3.5 3.5 3.5]]
+ e([1]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([2]) * 
[[10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]]
+ e([[1,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([1,2]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([[2,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [19]:
C = 2.5*rones(shx,shy)
print(C)

[[2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]]


In [20]:
print(B*C)

[[2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]]
+ e([1]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([2]) * 
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]
 [7.5 7.5 7.5]
 [7.5 7.5 7.5]]
+ e([[1,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([1,2]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([[2,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [21]:
print(C*B)

[[2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]]
+ e([1]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([2]) * 
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]
 [7.5 7.5 7.5]
 [7.5 7.5 7.5]]
+ e([[1,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([1,2]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([[2,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [22]:
print(B/C)

[[0.4 0.4 0.4]
 [0.4 0.4 0.4]
 [0.4 0.4 0.4]
 [0.4 0.4 0.4]]
+ e([1]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([2]) * 
[[1.2 1.2 1.2]
 [1.2 1.2 1.2]
 [1.2 1.2 1.2]
 [1.2 1.2 1.2]]
+ e([[1,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([1,2]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
+ e([[2,2]]) * 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [23]:
3/2.5

1.2