# File to test the behavior of the new data structure.
```
Mauricio Aristizabal Cano
June 15 2018
```


In [8]:
import numpy as np

path2dataFolder = '/Users/mauriaristi/Documents/src/otilib/build/data/v1.0/'

In [49]:
fulldir  = np.load(path2dataFolder + 'fulldir_n3_m10.npy')
multtabl = np.load(path2dataFolder + 'multtabl_n4_m10_0.npy')
ndirs    = np.load(path2dataFolder + 'ndirs_n4_m10.npy')


In [50]:
fulldir
multtabl
ndirs

array([  0,   1,   5,  15,  35,  70, 126, 210, 330, 495, 715],
      dtype=uint64)

In [18]:
from scipy.special import comb

In [51]:
m=5
n=4
comb(m+n-1,m-1,exact = True)


70

In [40]:
fulldir[5,:]

array([1, 1, 1, 3], dtype=uint16)

In [52]:
fulldir[multtabl[6-1,100-1]]


IndexError: index 245 is out of bounds for axis 0 with size 220

In [46]:
multtabl.shape


(10, 220)

In [56]:
fulldir[100]

array([2, 6, 8], dtype=uint16)