In [1]:
import otilib as oti
e = oti.e
np = oti.np
h = oti.get_dHelp()

In [3]:
np.set_printoptions(linewidth = 120)

In [15]:
a = oti.otinum(range(1,22),2)

In [17]:
print(a.toMatrix())

[[  1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  2.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  3.   2.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  4.   0.   0.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  5.   4.   0.   2.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  6.   0.   0.   4.   0.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  7.   0.   0.   0.   0.   0.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  8.   7.   0.   0.   0.   0.   2.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  9.   0.   0.   7.   0.   0.   4.   0.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.   0.   0.   0.   0.  

In [10]:
print(a)

0 + 1 * e([1]) + 0 * e([[1,2]]) + 0 * e([2]) + 0 * e([1,2]) + 0 * e([[2,2]]) + 0 * e([3]) + 0 * e([1,3]) + 0 * e([2,3]) + 0 * e([[3,2]]) + 0 * e([4]) + 0 * e([1,4]) + 0 * e([2,4]) + 0 * e([3,4]) + 0 * e([[4,2]]) + 0 * e([5]) + 0 * e([1,5]) + 0 * e([2,5]) + 0 * e([3,5]) + 0 * e([4,5]) + 0 * e([[5,2]]) 


In [12]:
len(a.coefs)

21

In [31]:
order = 2
ndir = 1000
a = (oti.findComb((2*ndir)+1,order))
b = (oti.findComb((ndir)+1,order))

print("2m: ",a)
print("m:  ",b)
print(a/b)


2m:  2003001
m:   501501
3.9940119760479043


In [30]:
order = 3
ndir = 5
N = oti.findComb((ndir)+1,order)

for i in range(0,N):
    expA = h.getExpA(i,order)
    dirA = h.getDirA(i,order)
#     print(i, expA)
#     print()
    mult = h.getMultiples(i,order)
#     print()


0 [0 0 0]


Number of multiples:  1

[[0 0 0]]

1 [1 0 0]


Number of multiples:  2

[[0 0 0]
 [1 0 0]]

2 [2 0 0]


Number of multiples:  3

[[0 0 0]
 [1 0 0]
 [2 0 0]]

3 [3 0 0]


Number of multiples:  4

[[0 0 0]
 [1 0 0]
 [2 0 0]
 [3 0 0]]

4 [1 0 0]


Number of multiples:  2

[[0 0 0]
 [1 0 0]]

5 [1 1 0]


Number of multiples:  4

[[0 0 0]
 [1 0 0]
 [0 1 0]
 [1 1 0]]

6 [2 1 0]


Number of multiples:  6

[[0 0 0]
 [1 0 0]
 [2 0 0]
 [0 1 0]
 [1 1 0]
 [2 1 0]]

7 [2 0 0]


Number of multiples:  3

[[0 0 0]
 [1 0 0]
 [2 0 0]]

8 [1 2 0]


Number of multiples:  6

[[0 0 0]
 [1 0 0]
 [0 1 0]
 [1 1 0]
 [0 2 0]
 [1 2 0]]

9 [3 0 0]


Number of multiples:  4

[[0 0 0]
 [1 0 0]
 [2 0 0]
 [3 0 0]]

10 [1 0 0]


Number of multiples:  2

[[0 0 0]
 [1 0 0]]

11 [1 1 0]


Number of multiples:  4

[[0 0 0]
 [1 0 0]
 [0 1 0]
 [1 1 0]]

12 [2 1 0]


Number of multiples:  6

[[0 0 0]
 [1 0 0]
 [2 0 0]
 [0 1 0]
 [1 1 0]
 [2 1 0]]

13 [1 1 0]


Number of multiples:  4

[[0 0 0]
 [1 0 0]
 [0 1 0]
 [

In [ ]:
h.getExpA(9,2)

In [ ]:
h.