In [1]:
# 1. SET GLOBAL PATH 
import sys
path2oti = '../../build/'
sys.path.append(path2oti) # Add path to OTI library.

In [2]:
from pyoti.dense import *

In [3]:
help(e)

Help on cython_function_or_method in module pyoti.dense:

e(hum_dir, order=0, nbases=0)
    PURPOSE:  To create an OTI number with value 1 at the specified
              direction, in a human friendly manner.



In [4]:
import pyoti.dense as oti
from pyoti.core import imdir

In [5]:
help(oti.sin)

Help on cython_function_or_method in module pyoti.dense:

sin(val)
    PURPOSE:  Mathematical function of sine for OTI numbers.



In [6]:
nb = 1
o  = 10

print( e( 1 , nbases=nb, order=o) )

0 + 1 * e([1]) + 0 * e([[1,2]]) + 0 * e([[1,3]]) + 0 * e([[1,4]]) + 0 * e([[1,5]]) + 0 * e([[1,6]]) + 0 * e([[1,7]]) + 0 * e([[1,8]]) + 0 * e([[1,9]]) + 0 * e([[1,10]])


In [7]:
x = 0.5 +  e( 1 , nbases=nb, order=o)
print(x)

0.5 + 1 * e([1]) + 0 * e([[1,2]]) + 0 * e([[1,3]]) + 0 * e([[1,4]]) + 0 * e([[1,5]]) + 0 * e([[1,6]]) + 0 * e([[1,7]]) + 0 * e([[1,8]]) + 0 * e([[1,9]]) + 0 * e([[1,10]])


In [8]:
print(sin(x**2))

0.247404 + 0.968912 * e([1]) + 0.84521 * e([[1,2]]) - 0.408889 * e([[1,3]]) - 0.59785 * e([[1,4]]) - 0.435148 * e([[1,5]]) - 0.0596067 * e([[1,6]]) + 0.119723 * e([[1,7]]) + 0.0845574 * e([[1,8]]) + 0.0295136 * e([[1,9]]) - 0.00361277 * e([[1,10]])


In [9]:
%timeit sin(x**2)

17.1 µs ± 149 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
fx = sin(x**2)

In [11]:
imdir([ 1, 2 ])

[1, 2]

In [12]:
fx.get_deriv(imdir([ [1, 2] ])) # Extraer segunda derivada con respecto a x

1.6904208841667665

In [13]:
import math

x0 = 0.5
f = math.sin(x0**2)
df = math.cos(x0**2)*2*x0
ddf = 2*math.cos(x0**2) - 4*math.sin(x0**2)*x0**2

def evalf():
    f = math.sin(x0**2)
    df = math.cos(x0**2)*2*x0
    ddf = 2*math.cos(x0**2) - 4*math.sin(x0**2)*x0**2


print(f)
print(df)
print(ddf)

0.24740395925452294
0.9689124217106447
1.6904208841667665


In [14]:
0.84521*2

1.69042

In [15]:
%timeit evalf()

1.57 µs ± 10 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [33]:
import sympy as sym

xs, ys = sym.symbols('x y')

fs = sym.sin(xs**2)


fs_10 = fs.diff(xs,3)



In [17]:
print(fs_10)

-4*x*(2*x**2*cos(x**2) + 3*sin(x**2))


In [18]:
%timeit fs.diff(xs,10)

5.71 ms ± 21.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
fs_10.replace(xs,0.5).doit()

-2.45333617723778

In [20]:
fx.get_deriv( imdir( [ [1,10] ] ) )

-13110.008022904183

In [21]:
print(fx)

0.247404 + 0.968912 * e([1]) + 0.84521 * e([[1,2]]) - 0.408889 * e([[1,3]]) - 0.59785 * e([[1,4]]) - 0.435148 * e([[1,5]]) - 0.0596067 * e([[1,6]]) + 0.119723 * e([[1,7]]) + 0.0845574 * e([[1,8]]) + 0.0295136 * e([[1,9]]) - 0.00361277 * e([[1,10]])


In [22]:
(13110.0080229042-13110.008022904183)/13110.0080229042

1.248733380125433e-15

In [47]:
# Ejemplo por multiduals

nb = 2
o  = 10

x = 0.5 + e( 1 , nbases=nb, order=o) #+ e( 2 , nbases=nb, order=o) + e( 3 , nbases=nb, order=o)
y = 0.3 + e( 2 , nbases=nb, order=o)

y0 = 0.3
print(x)

0.5 + 1 * e([1]) + 0 * e([2]) + 0 * e([[1,2]]) + 0 * e([1,2]) + 0 * e([[2,2]]) + 0 * e([[1,3]]) + 0 * e([[1,2],2]) + 0 * e([1,[2,2]]) + 0 * e([[2,3]]) + 0 * e([[1,4]]) + 0 * e([[1,3],2]) + 0 * e([[1,2],[2,2]]) + 0 * e([1,[2,3]]) + 0 * e([[2,4]]) + 0 * e([[1,5]]) + 0 * e([[1,4],2]) + 0 * e([[1,3],[2,2]]) + 0 * e([[1,2],[2,3]]) + 0 * e([1,[2,4]]) + 0 * e([[2,5]]) + 0 * e([[1,6]]) + 0 * e([[1,5],2]) + 0 * e([[1,4],[2,2]]) + 0 * e([[1,3],[2,3]]) + 0 * e([[1,2],[2,4]]) + 0 * e([1,[2,5]]) + 0 * e([[2,6]]) + 0 * e([[1,7]]) + 0 * e([[1,6],2]) + 0 * e([[1,5],[2,2]]) + 0 * e([[1,4],[2,3]]) + 0 * e([[1,3],[2,4]]) + 0 * e([[1,2],[2,5]]) + 0 * e([1,[2,6]]) + 0 * e([[2,7]]) + 0 * e([[1,8]]) + 0 * e([[1,7],2]) + 0 * e([[1,6],[2,2]]) + 0 * e([[1,5],[2,3]]) + 0 * e([[1,4],[2,4]]) + 0 * e([[1,3],[2,5]]) + 0 * e([[1,2],[2,6]]) + 0 * e([1,[2,7]]) + 0 * e([[2,8]]) + 0 * e([[1,9]]) + 0 * e([[1,8],2]) + 0 * e([[1,7],[2,2]]) + 0 * e([[1,6],[2,3]]) + 0 * e([[1,5],[2,4]]) + 0 * e([[1,4],[2,5]]) + 0 * e([[1,3],[

In [31]:
%timeit sin(x**2)

4.94 µs ± 83.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [34]:
fs = sym.sin(xs**2*ys)/ys**2

In [51]:
fs.diff(xs,0).diff(ys,10).replace(xs,x0).replace(ys,y0).doit()
 

512117055326.932

In [48]:
print(sin(x**2*y)/y**2)

0.832552 + 3.32396 * e([1]) - 2.78038 * e([2]) + 3.2865 * e([[1,2]]) - 11.1423 * e([1,2]) + 9.25927 * e([[2,2]]) - 0.124789 * e([[1,3]]) - 11.267 * e([[1,2],2]) + 37.0372 * e([1,[2,2]]) - 30.8642 * e([[2,3]]) - 0.186762 * e([[1,4]]) - 0.414559 * e([[1,3],2]) + 37.0384 * e([[1,2],[2,2]]) - 123.457 * e([1,[2,3]]) + 102.881 * e([[2,4]]) - 0.14823 * e([[1,5]]) - 0.617625 * e([[1,4],2]) + 0.00702173 * e([[1,3],[2,2]]) - 123.455 * e([[1,2],[2,3]]) + 411.523 * e([1,[2,4]]) - 342.936 * e([[2,5]]) - 0.0470525 * e([[1,6]]) - 0.482313 * e([[1,5],2]) + 0.024557 * e([[1,4],[2,2]]) + 0.00778078 * e([[1,3],[2,3]]) + 411.523 * e([[1,2],[2,4]]) - 1371.74 * e([1,[2,5]]) + 1143.12 * e([[2,6]]) + 0.00336208 * e([[1,7]]) - 0.13723 * e([[1,6],2]) + 0.0588532 * e([[1,5],[2,2]]) + 0.0271693 * e([[1,4],[2,3]]) - 5.28323e-05 * e([[1,3],[2,4]]) - 1371.74 * e([[1,2],[2,5]]) + 4572.47 * e([1,[2,6]]) - 3810.39 * e([[2,7]]) + 0.00250865 * e([[1,8]]) + 0.0335348 * e([[1,7],2]) + 0.0978097 * e([[1,6],[2,2]]) + 0.06492

In [42]:
9.25927*2

18.51854

In [50]:
(sin(x**2*y)/y**2).get_deriv( imdir([[2,10]]) )

512117055326.6407

In [49]:
x

otinum(0.5, ndir: 65, order: 10)

In [52]:
(512117055326.932-512117055326.6407)/512117055326.932

5.688558850969585e-13

In [53]:
65**5

1160290625

In [54]:
import numpy as np

X = np.zeros((2,2))
X


array([[0., 0.],
       [0., 0.]])

In [55]:
X[0,0] = x0
X[1,1] = x0
X[1,0] = 1.
X

array([[0.5, 0. ],
       [1. , 0.5]])

In [58]:
import scipy as sci
SIN =  sci.linalg.sinm
DOT = np.dot

In [59]:
# sin(x**2) --> 
#                 x**2   = DOT(X,X)  <- Producto interior
#                 sin(y) = SIN(Y)    <- Seno matricial

F = SIN( DOT(X,X) )
F

array([[0.24740396, 0.        ],
       [0.96891242, 0.24740396]])

In [ ]:
0.24740395925452294
0.9689124217106447