In [1]:
import numpy as np

In [2]:
import gmsh
gmsh.initialize()

# simple square mesh generator.
# Lets create a simple square element:

model = gmsh.model 
geo   = model.geo
option= gmsh.option



hight = 1
width = 1
he    = 1.0/5

P1 = geo.addPoint(     -width/2.0,    hight/2.0, 0, he, 1)
P2 = geo.addPoint(     -width/2.0,   -hight/2.0, 0, he, 2)
P3 = geo.addPoint(width-width/2.0,    hight/2.0, 0, he, 3)
P4 = geo.addPoint(width-width/2.0,   -hight/2.0, 0, he, 4)

L1 = geo.addLine(P1,P2) # Left
L2 = geo.addLine(P2,P4) # bottom
L3 = geo.addLine(P4,P3) # right
L4 = geo.addLine(P3,P1) # up

loop1 = geo.addCurveLoop([L1,L2,L3,L4])

surface = geo.addPlaneSurface([loop1])

model.addPhysicalGroup(0, [P2], 200 )
model.addPhysicalGroup(1, [L1], 201 )
model.addPhysicalGroup(1, [L2], 202 )
model.addPhysicalGroup(1, [L3], 203 )
model.addPhysicalGroup(1, [L4], 204 )
model.addPhysicalGroup(2, [surface], 301 )

model.setPhysicalName(0,200,"Pressure")
model.setPhysicalName(1,201,"left")
model.setPhysicalName(1,202,"bottom")
model.setPhysicalName(1,203,"right")
model.setPhysicalName(1,204,"up")
model.setPhysicalName(2,301,"fluid")

geo.synchronize()

# model.mesh.setRecombine(2)
option.setNumber('Mesh.ElementOrder',2)


model.mesh.generate(2)


mesh = model.mesh

elementTypes, elementTags, elemNodeTags = mesh.getElements()
# elementTypes: Is a 1D np.array that contains the types of elements in the mesh.
# elementTags:  Is a list containing the index of each element in the mesh.
# elemNodeTags: Is a list containing the index of the corresponding nodes for each element. 
#               Every element in the list is a 1D array of the indices. This must be reshaped.


nodeTags, coord, parametricCoord = mesh.getNodes()

# Get the physical groups and its properties.
physicalGroups = model.getPhysicalGroups()

physicalNames ={}
nodesPerPhysicalGroup = []

for i in range(len(physicalGroups)):
    # Get the name:
    physicalNames[model.getPhysicalName(*physicalGroups[i])]=physicalGroups[i]
    nodesPerPhysicalGroup.append(mesh.getNodesForPhysicalGroup(*physicalGroups[i])[0])
    
# Get properties.
print( mesh.getElementType('triangle',10) )

gmsh.write("test.msh")


46


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/ctypeslib.py:523: RuntimeWarning: A builtin ctypes object gave a PEP3118 format string that does not match its itemsize, so a best-guess will be made of the data type. Newer versions of python may behave correctly.
  return array(obj, copy=False)


In [7]:
model.getEntitiesForPhysicalGroup(1,201)

mesh.getElements(1,4)

(array([8], dtype=int32),
 [array([17, 18, 19, 20, 21], dtype=uint64)],
 [array([ 3, 32, 36, 32, 33, 37, 33, 34, 38, 34, 35, 39, 35,  1, 40],
        dtype=uint64)])

In [3]:
nodesPerPhysicalGroup

[array([2], dtype=uint64),
 array([ 5,  1,  2,  6,  7,  8,  9, 11, 12, 13, 10], dtype=uint64),
 array([ 4,  2, 14, 15, 16, 17, 20, 21, 22, 18, 19], dtype=uint64),
 array([ 4,  3, 23, 24, 25, 26, 28, 30, 29, 31, 27], dtype=uint64),
 array([ 1,  3, 32, 33, 34, 35, 38, 37, 36, 39, 40], dtype=uint64),
 array([ 5,  1,  2,  6,  7,  8,  9, 11, 12, 13, 10], dtype=uint64)]

In [6]:
model.getPhysicalName(1,201)

'left'

In [7]:
physicalGroups

[(0, 200), (1, 201), (1, 202), (1, 203), (1, 204), (1, 301)]

In [8]:
physicalNames

{'Pressure': (0, 200),
 'left': (1, 201),
 'bottom': (1, 202),
 'right': (1, 203),
 'up': (1, 204),
 'fluid': (1, 301)}

In [53]:
elementTypes

array([ 8,  9, 15], dtype=int32)

In [54]:
elemNodeTags

[array([ 1,  5,  9,  5,  6, 10,  6,  7, 11,  7,  8, 12,  8,  2, 13,  2, 14,
        18, 14, 15, 19, 15, 16, 20, 16, 17, 21, 17,  4, 22,  4, 23, 27, 23,
        24, 28, 24, 25, 29, 25, 26, 30, 26,  3, 31,  3, 32, 36, 32, 33, 37,
        33, 34, 38, 34, 35, 39, 35,  1, 40], dtype=uint64),
 array([ 42,  48,  54,  66,  67,  68,  54,  48,  55,  67,  69,  70,  43,
         49,  56,  71,  72,  73,  49,  54,  56,  74,  75,  72,  55,  46,
         57,  76,  77,  78,  44,  46,  55,  79,  76,  80,  47,  56,  57,
         81,  82,  83,  45,  47,  57,  84,  83,  85,  24,  25,  46,  29,
         86,  87,  33,  34,  47,  38,  88,  89,  15,  16,  48,  20,  90,
         91,   6,   7,  49,  11,  92,  93,   2,  14,  50,  18,  94,  95,
          8,   2,  50,  13,  95,  96,   1,   5,  51,   9,  97,  98,  35,
          1,  51,  40,  98,  99,   4,  23,  52,  27, 100, 101,  17,   4,
         52,  22, 101, 102,   3,  32,  53,  36, 103, 104,  26,   3,  53,
         31, 104, 105,  24,  46,  64,  87, 106, 107,  3

In [55]:

elementTypes 
number_of_elementTypes = len(elementTypes)
number_of_elements_per_type = np.zeros(number_of_elementTypes,dtype=np.uint64)
for i in range(number_of_elementTypes):
    number_of_elements_per_type[i]=len(elementTags[i])

In [56]:
number_of_elements_per_type

array([20, 68,  4], dtype=uint64)

In [57]:
elemNodeTags_reshaped = []

for i in range(number_of_elementTypes):
    
    print(int(elemNodeTags[i].size//number_of_elements_per_type[i]))
    
    elemNodeTags_reshaped.append(elemNodeTags[i].reshape(number_of_elements_per_type[i],int(elemNodeTags[i].size//number_of_elements_per_type[i])))

# end for

3
6
1


In [25]:
def get_elements( mesh, dim=-1, tag=-1 ):
    
    elTypes, elTags, nodes = mesh.getElements(dim=dim,tag=tag)
    for i in range(len(elTypes)):
        numelsi = elTags[i].size
        nodes[i] = nodes[i].reshape((numelsi,int(nodes[i].size// numelsi))) 
        
    return elTypes,elTags,nodes
    
    

In [29]:
get_elements( mesh, dim=1)

(array([8], dtype=int32),
 [array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20, 21], dtype=uint64)],
 [array([[ 1,  5,  9],
         [ 5,  6, 10],
         [ 6,  7, 11],
         [ 7,  8, 12],
         [ 8,  2, 13],
         [ 2, 14, 18],
         [14, 15, 19],
         [15, 16, 20],
         [16, 17, 21],
         [17,  4, 22],
         [ 4, 23, 27],
         [23, 24, 28],
         [24, 25, 29],
         [25, 26, 30],
         [26,  3, 31],
         [ 3, 32, 36],
         [32, 33, 37],
         [33, 34, 38],
         [34, 35, 39],
         [35,  1, 40]], dtype=uint64)])

In [30]:
nodeTags

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157], dtype=uint64)

In [21]:
np.max(nodeTags)

157

In [31]:
np.array(range(nodeTags.size),dtype=np.uint64)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156], dtype=uint64)

array([-5.00000000e-01,  5.00000000e-01,  0.00000000e+00, -5.00000000e-01,
       -5.00000000e-01,  0.00000000e+00,  5.00000000e-01,  5.00000000e-01,
        0.00000000e+00,  5.00000000e-01, -5.00000000e-01,  0.00000000e+00,
       -5.00000000e-01,  3.00000000e-01,  0.00000000e+00, -5.00000000e-01,
        1.00000000e-01,  0.00000000e+00, -5.00000000e-01, -1.00000000e-01,
        0.00000000e+00, -5.00000000e-01, -3.00000000e-01,  0.00000000e+00,
       -5.00000000e-01,  4.00000000e-01,  0.00000000e+00, -5.00000000e-01,
        2.00000000e-01,  0.00000000e+00, -5.00000000e-01,  1.38722367e-12,
        0.00000000e+00, -5.00000000e-01, -2.00000000e-01,  0.00000000e+00,
       -5.00000000e-01, -4.00000000e-01,  0.00000000e+00, -3.00000000e-01,
       -5.00000000e-01,  0.00000000e+00, -1.00000000e-01, -5.00000000e-01,
        0.00000000e+00,  1.00000000e-01, -5.00000000e-01,  0.00000000e+00,
        3.00000000e-01, -5.00000000e-01,  0.00000000e+00, -4.00000000e-01,
       -5.00000000e-01,  

In [24]:
nodeTags-1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156], dtype=uint64)

In [22]:
nodeTags.size

157

In [64]:
nodeTags_sorted

In [ ]:
gmsh.finalize()