In [ ]:


import gmsh

# Allways initialize gmsh if not so.

In [2]:
# gmsh.finalize()
gmsh.initialize()
# gmsh.fltk.initialize()

# Lets create a simple square element:
model = gmsh.model
geo   = model.geo
option= gmsh.option



hight = 1
width = 1
he    = 1.0/30

P1 = geo.addPoint(     -width/2.0,    hight/2.0, 0, he, 1)
P2 = geo.addPoint(     -width/2.0,   -hight/2.0, 0, he, 2)
P3 = geo.addPoint(width-width/2.0,    hight/2.0, 0, he, 3)
P4 = geo.addPoint(width-width/2.0,   -hight/2.0, 0, he, 4)

L1 = geo.addLine(P1,P2) # Left
L2 = geo.addLine(P2,P4) # bottom
L3 = geo.addLine(P4,P3) # right
L4 = geo.addLine(P3,P1) # up

loop1 = geo.addCurveLoop([L1,L2,L3,L4])

surface = geo.addPlaneSurface([loop1])





model.addPhysicalGroup(0, [P2], 200 )
model.addPhysicalGroup(1, [L1], 201 )
model.addPhysicalGroup(1, [L2], 202 )
model.addPhysicalGroup(1, [L3], 203 )
model.addPhysicalGroup(1, [L4], 204 )
model.addPhysicalGroup(1, [surface], 301 )

model.setPhysicalName(0,200,"Pressure")
model.setPhysicalName(0,201,"left")
model.setPhysicalName(0,202,"bottom")
model.setPhysicalName(0,203,"right")
model.setPhysicalName(0,204,"up")
model.setPhysicalName(0,301,"fluid")

geo.synchronize()

model.mesh.setRecombine(2,)
option.setNumber('Mesh.ElementOrder',2)


model.mesh.generate(2)


# gmsh.fltk.run()

# gmsh.fltk.finalize()

# gmsh.finalize()

ValueError: ('gmshModelMeshSetRecombine returned non-zero error code: ', 2)

In [3]:
mesh = model.mesh

In [4]:
elementTypes, elementTags, nodeTags = mesh.getElements()

In [5]:
elementTypes

array([ 8,  9, 15], dtype=int32)

In [8]:
len(elementTags)


3

In [10]:
elementTags[0].size

120

In [11]:
nodeTags[0].size


360

In [30]:
mesh.getElementType('triangle',10)

46

In [7]:
mesh.getNodes()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/ctypeslib.py:523: RuntimeWarning: A builtin ctypes object gave a PEP3118 format string that does not match its itemsize, so a best-guess will be made of the data type. Newer versions of python may behave correctly.
  return array(obj, copy=False)


(array([   1,    2,    3, ..., 4763, 4764, 4765], dtype=uint64),
 array([-0.5       ,  0.5       ,  0.        , ..., -0.12989261,
         0.11177698,  0.        ]),
 array([], dtype=float64))

In [5]:
elementName, dim,order,numNodes,nodeCoord = mesh.getElementProperties(8)
for etype in elementTypes:
    props = mesh.getElementProperties(etype) 
    string = ""
    string += "Name:  -- "+str(props[0]) + "\n"
    string += "ndim:  -- "+str(props[1]) + "\n"
    string += "order: -- "+str(props[2]) + "\n"
    string += "nNodes:-- "+str(props[3]) + "\n"
    if props[1]!=0:
        string += "coords:\n"+str(props[4].reshape(props[4].size//props[1],props[1])) 
    else:
        string += "coords:\n"+str(props[4]) 
        
        

    print(string)
    print()
    

NameError: name 'elementTypes' is not defined

In [3]:
model.getPhysicalGroups()


[(0, 200), (1, 201), (1, 202), (1, 203), (1, 204), (1, 301)]

In [3]:
gmsh.write("mesh_test.msh")

In [5]:
gmsh.finalize()