In [1]:


import gmsh

# Allways initialize gmsh if not so.

In [2]:
# gmsh.finalize()
gmsh.initialize()
# gmsh.fltk.initialize()

# Lets create a simple square element:
model = gmsh.model
geo   = model.geo
option= gmsh.option



hight = 1
width = 1
he    = 1.0/30

P1 = geo.addPoint(     -width/2.0,    hight/2.0, 0, he, 1)
P2 = geo.addPoint(     -width/2.0,   -hight/2.0, 0, he, 2)
P3 = geo.addPoint(width-width/2.0,    hight/2.0, 0, he, 3)
P4 = geo.addPoint(width-width/2.0,   -hight/2.0, 0, he, 4)

L1 = geo.addLine(P1,P2) # Left
L2 = geo.addLine(P2,P4) # bottom
L3 = geo.addLine(P4,P3) # right
L4 = geo.addLine(P3,P1) # up

loop1 = geo.addCurveLoop([L1,L2,L3,L4])

surface = geo.addPlaneSurface([loop1],tag = 150)

model.addPhysicalGroup(0, [P2], 200 )
model.addPhysicalGroup(1, [L1], 201 )
model.addPhysicalGroup(1, [L2], 202 )
model.addPhysicalGroup(1, [L3], 203 )
model.addPhysicalGroup(1, [L4], 204 )
model.addPhysicalGroup(2, [surface], 301 )

model.setPhysicalName(0,200,"Pressure")
model.setPhysicalName(0,201,"left")
model.setPhysicalName(0,202,"bottom")
model.setPhysicalName(0,203,"right")
model.setPhysicalName(0,204,"up")
model.setPhysicalName(0,301,"fluid")


geo.synchronize()

# model.mesh.setRecombine(2)
option.setNumber('Mesh.ElementOrder',2)


model.mesh.generate(2)


# gmsh.fltk.run()

# gmsh.fltk.finalize()

# gmsh.finalize()

In [3]:
model = gmsh.model
mesh = gmsh.model.mesh

In [4]:
pg = model.getPhysicalGroups()
pg

[(0, 200), (1, 201), (1, 202), (1, 203), (1, 204), (2, 301)]

In [5]:
i = 1
entities = []

for pgp in pg:
    entities.append(model.getEntitiesForPhysicalGroup(*pgp))
entities

[array([2], dtype=int32),
 array([1], dtype=int32),
 array([2], dtype=int32),
 array([3], dtype=int32),
 array([4], dtype=int32),
 array([150], dtype=int32)]

In [6]:
entities

[array([2], dtype=int32),
 array([1], dtype=int32),
 array([2], dtype=int32),
 array([3], dtype=int32),
 array([4], dtype=int32),
 array([1], dtype=int32)]

In [8]:

for i in range(len(entities)):
    elementTypes, elementTags, nodeTags = mesh.getElements(dim=pg[i][0],tag=entities[i])
    print(elementTypes, elementTags, nodeTags)

[15] [array([1], dtype=uint64)] [array([2], dtype=uint64)]
[8] [array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], dtype=uint64)] [array([ 1,  5, 34,  5,  6, 35,  6,  7, 36,  7,  8, 37,  8,  9, 38,  9, 10,
       39, 10, 11, 40, 11, 12, 41, 12, 13, 42, 13, 14, 43, 14, 15, 44, 15,
       16, 45, 16, 17, 46, 17, 18, 47, 18, 19, 48, 19, 20, 49, 20, 21, 50,
       21, 22, 51, 22, 23, 52, 23, 24, 53, 24, 25, 54, 25, 26, 55, 26, 27,
       56, 27, 28, 57, 28, 29, 58, 29, 30, 59, 30, 31, 60, 31, 32, 61, 32,
       33, 62, 33,  2, 63], dtype=uint64)]
[8] [array([32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61], dtype=uint64)] [array([  2,  64,  93,  64,  65,  94,  65,  66,  95,  66,  67,  96,  67,
        68,  97,  68,  69,  98,  69,  70,  99,  70,  71, 100,  71,  72,
       101,  72,  73, 102,  73,  74, 103,  74,  75, 104,  75,  76, 

In [7]:
elementTypes

NameError: name 'elementTypes' is not defined

In [13]:
elementTags

[array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
         41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
         67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
        106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
        119, 120, 121], dtype=uint64)]

In [8]:
len(elementTags)


3

In [10]:
elementTags[0].size

120

In [11]:
nodeTags[0].size


360

In [30]:
mesh.getElementType('triangle',10)

46

In [7]:
mesh.getNodes()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/ctypeslib.py:523: RuntimeWarning: A builtin ctypes object gave a PEP3118 format string that does not match its itemsize, so a best-guess will be made of the data type. Newer versions of python may behave correctly.
  return array(obj, copy=False)


(array([   1,    2,    3, ..., 4763, 4764, 4765], dtype=uint64),
 array([-0.5       ,  0.5       ,  0.        , ..., -0.12989261,
         0.11177698,  0.        ]),
 array([], dtype=float64))

In [5]:
elementName, dim,order,numNodes,nodeCoord = mesh.getElementProperties(8)
for etype in elementTypes:
    props = mesh.getElementProperties(etype) 
    string = ""
    string += "Name:  -- "+str(props[0]) + "\n"
    string += "ndim:  -- "+str(props[1]) + "\n"
    string += "order: -- "+str(props[2]) + "\n"
    string += "nNodes:-- "+str(props[3]) + "\n"
    if props[1]!=0:
        string += "coords:\n"+str(props[4].reshape(props[4].size//props[1],props[1])) 
    else:
        string += "coords:\n"+str(props[4]) 
        
        

    print(string)
    print()
    

NameError: name 'elementTypes' is not defined

In [3]:
model.getPhysicalGroups()


[(0, 200), (1, 201), (1, 202), (1, 203), (1, 204), (1, 301)]

In [3]:
gmsh.write("mesh_test.msh")

In [5]:
gmsh.finalize()