# Readme: Utilities in PyOTI library.
```
Mauricio Aristizabal Cano
07 Apr 2020
```


# 1. Accessing the library


In [1]:
# 1. SET GLOBAL PATH 
import sys
path2oti = '../../../build/'
sys.path.append(path2oti) # Add path to OTI library.


# Import core module only from pyoti.
import pyoti.core as oti
np = oti.np

## 2. Getting the utility libraries:


In [2]:
# Location of the library can be accesed by:
oti.whereotilib.getpath()

'/Users/maristi7/coding/otilib/build/pyoti/'

In [4]:
oti.ndir_order( 5, 3)

35

In [5]:
print("Multiplication table for order 2 directions:")
mult_table = np.load(path2oti+'data/multtabl_n2_0.npy')
mult_table[:3,:3]

Multiplication table for order 2 directions:


array([[0, 1, 3],
       [1, 2, 4],
       [3, 4, 5]], dtype=uint64)

In [13]:
print("Multiplication table for order 3 directions:")
mult_table = np.load('/Users/maristi7/coding/otilib/build/data/multtabl_n3_0.npy')
mult_table[:3,:6]

Multiplication table for order 3 directions:


array([[0, 1, 2, 4, 5, 7],
       [1, 2, 3, 5, 6, 8],
       [4, 5, 6, 7, 8, 9]], dtype=uint64)

In [46]:
o1   = 2
m1   = 3
n1   = oti.ndir_order( m1, o1)

o2   = 2
m2   = m1
n2   = oti.ndir_order( m2, o2)

o_res = o1 + o2

o_min = int(o1 - 1)

# print(path2oti+'data/multtabl_n'+str(o_res)+'_'+str(o_min)+'.npy')

mult_table = np.load(path2oti+'data/multtabl_n'+str(o_res)+'_'+str(o_min)+'.npy')[:n1,:n2]

# print(mult_table)
string = ""

for i1 in range(-1,n1): 
        
    for i2 in range(-1,n2):
        
        if i2 == -1 and not i1 == -1:
            string += oti.get_latex_dir(i1,o1)
        elif i1 == -1 and not i2 == -1:
            string += oti.get_latex_dir(i2,o2) 
        elif i1 != -1 and i2 != -1:
            string+= "\\fill[white!0] circle[radius=\\radius,at="
            pos = "(m-"
            pos += str(int(i1+1))
            pos += "-"
            pos += str(int(i2+1))
            pos += ")"
            string += pos
            string += "] node[black] at "
            string += pos
            string += "{$"
            string += oti.get_latex_dir(mult_table[i1,i2],o_res)
            string += "$};"
        # end if
            
        string += "\n"    

    
    # end for 
    
#     string = string[:-1] + "\n"
    
# end for 

string = string[:-1]

# print("\\begin{bmatrix}")        
print(string)
# print("\end{bmatrix}")        


\epsilon_{1}^{2}
\epsilon_{1}\epsilon_{2}
\epsilon_{2}^{2}
\epsilon_{1}\epsilon_{3}
\epsilon_{2}\epsilon_{3}
\epsilon_{3}^{2}
\epsilon_{1}^{2}
\fill[white!0] circle[radius=\radius,at=(m-1-1)] node[black] at (m-1-1){$\epsilon_{1}^{4}$};
\fill[white!0] circle[radius=\radius,at=(m-1-2)] node[black] at (m-1-2){$\epsilon_{1}^{3}\epsilon_{2}$};
\fill[white!0] circle[radius=\radius,at=(m-1-3)] node[black] at (m-1-3){$\epsilon_{1}^{2}\epsilon_{2}^{2}$};
\fill[white!0] circle[radius=\radius,at=(m-1-4)] node[black] at (m-1-4){$\epsilon_{1}^{3}\epsilon_{3}$};
\fill[white!0] circle[radius=\radius,at=(m-1-5)] node[black] at (m-1-5){$\epsilon_{1}^{2}\epsilon_{2}\epsilon_{3}$};
\fill[white!0] circle[radius=\radius,at=(m-1-6)] node[black] at (m-1-6){$\epsilon_{1}^{2}\epsilon_{3}^{2}$};
\epsilon_{1}\epsilon_{2}
\fill[white!0] circle[radius=\radius,at=(m-2-1)] node[black] at (m-2-1){$\epsilon_{1}^{3}\epsilon_{2}$};
\fill[white!0] circle[radius=\radius,at=(m-2-2)] node[black] at (m-2-2){$\epsilon_{1}^{2

In [24]:
mult_table

array([[0, 1, 2, 4, 5, 7],
       [1, 2, 3, 5, 6, 8],
       [4, 5, 6, 7, 8, 9]], dtype=uint64)

6

## 4. Direction helper ```h```

In order to get the direction helper ```h``` do the following:

In [5]:
h = oti.get_dHelp()

### 4.1 Getting the text form of a direction

In [9]:
h.get_fulldir(4,3)

array([1, 1, 3], dtype=uint16)

In [7]:
h.get_str_fulldir(4,3)

'[1,1,3]'