In [1]:
# 1. SET GLOBAL PATH 
import sys
path2oti = '../../../build/'
sys.path.append(path2oti) # Add path to OTI library.

from IPython.display import display, Math

from pyoti.core import dhelp_get_matrix_form

def display_string(string, head = "", tail = ""):
    display(Math(head+string+tail))
# end 

In [6]:
# Generate matrix forms

n_variables = 3
deriv_order = 3

latex = dhelp_get_matrix_form( n_variables, deriv_order, export_latex=True)
display_string(latex, head = '\\begin{bmatrix}', tail = '\\end{bmatrix}')

<IPython.core.display.Math object>

In [7]:
head = "\\begin{bmatrix}\n"
tail = "\\end{bmatrix}\n"
print(head+latex+tail)

\begin{bmatrix}
_{\mbox{Re}} & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
\epsilon_{1} & _{\mbox{Re}} & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
\epsilon_{2} & 0 & _{\mbox{Re}} & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
\epsilon_{3} & 0 & 0 & _{\mbox{Re}} & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
\epsilon_{1}^{2} & \epsilon_{1} & 0 & 0 & _{\mbox{Re}} & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
\epsilon_{1}\epsilon_{2} & \epsilon_{2} & \epsilon_{1} & 0 & 0 & _{\mbox{Re}} & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
\epsilon_{2}^{2} & 0 & \epsilon_{2} & 0 & 0 & 0 & _{\mbox{Re}} & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
\epsilon_{1}\epsilon_{3} & \epsilon_{3} & 0 & \epsilon_{1} & 0 & 0 & 0 & _{\mbox{Re}} & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
\epsilon_{2}\epsilon_{3} & 0 & \epsilon_{3} & \epsilon_{2} & 0 & 0 & 0 & 

In [7]:
import pyoti.dense as oti
import pyoti.core as otic

np    = oti.np

shape = 10

A = oti.eye( shape,   nbases=n_variables,order=deriv_order)
b = oti.ones(shape, 1,nbases=n_variables,order=deriv_order)*50


In [8]:
A

omat<shape: (10, 10), ndir: 5, order: 5, re:
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])>

In [11]:
b

omat<shape: (10, 1), ndir: 5, order: 5, re:
array([[50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.]])>

In [12]:
x = oti.solve(A,b)

In [13]:
%timeit oti.solve(A,b)

505 µs ± 2.82 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
%timeit oti.dot(A,b)

2.24 µs ± 15 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [51]:
Ar = A.get_im(0)
br = b.get_im(0)

In [52]:
Ar

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [53]:
br

array([[50.],
       [50.],
       [50.],
       ...,
       [50.],
       [50.],
       [50.]])

In [54]:
%timeit np.linalg.solve(Ar,br)

7.99 s ± 212 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [59]:
8.67/7.99 #5 derivs , 7.7s (2var, 2ord)
# 1.1259

1.0851063829787233

In [56]:
9.41/7.99 # 14 derivs, 7.7s (4vars, 2ord)
# 1.222

1.1777221526908637

In [58]:
(9.41-8.67)/8.67

0.08535178777393312

In [62]:
K = oti.spr_omat((3,3), nbases = n_variables, order=deriv_order)

In [67]:
K[2,2] = 5.3
K[1,2] = 8.5 + 5 * oti.e([1,4])

print(K)

< spr_omat class, shape: (3,3), ndir: 14, nbases: 4, order: 2, 
  (1, 2)	8.5
  (2, 2)	5.3
+ e([1]) * 

+ e([2]) * 

+ e([3]) * 

+ e([4]) * 

+ e([[1,2]]) * 

+ e([1,2]) * 

+ e([[2,2]]) * 

+ e([1,3]) * 

+ e([2,3]) * 

+ e([[3,2]]) * 

+ e([1,4]) * 
  (1, 2)	5.0
+ e([2,4]) * 

+ e([3,4]) * 

+ e([[4,2]]) * 

 >


In [23]:
alpha = 1+oti.e(1,nbases=n_variables,order=deriv_order)

A[0,0] = 3*alpha
A[0,1] = 2.0
A[1,0] = 0.0
A[1,1] = 4/alpha
print("A:\n",A)

b[0,0] = 2.0
b[1,0] = 3.0
print("b:\n",b)

A:
 [[3. 2.]
 [0. 4.]]
+ e([1]) * 
[[ 3.  0.]
 [ 0. -4.]]
+ e([2]) * 
[[0. 0.]
 [0. 0.]]
+ e([[1,2]]) * 
[[0. 0.]
 [0. 4.]]
+ e([1,2]) * 
[[0. 0.]
 [0. 0.]]
+ e([[2,2]]) * 
[[0. 0.]
 [0. 0.]]

b:
 [[2.]
 [3.]]
+ e([1]) * 
[[0.]
 [0.]]
+ e([2]) * 
[[0.]
 [0.]]
+ e([[1,2]]) * 
[[0.]
 [0.]]
+ e([1,2]) * 
[[0.]
 [0.]]
+ e([[2,2]]) * 
[[0.]
 [0.]]



In [5]:
x = oti.solve(A,b)

print(x.get_deriv([[1,5]]))

[[-80.]
 [  0.]]


In [8]:
%timeit oti.solve(A,b)


472 µs ± 8.54 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
Ar = np.array([[3,2],[0,4]])
Ar
br = np.array([[2],[3]])
br

array([[2],
       [3]])

In [16]:
xr = np.linalg.solve(Ar,br)
xr

array([[0.16666667],
       [0.75      ]])

In [17]:
Ap = np.array([[3,0],[0,-4]])
bp = np.array([[0],[0]])

print(bp-np.dot(Ap,xr))
xp = np.linalg.solve(Ar,bp-np.dot(Ap,xr))
print(xp)

[[-0.5]
 [ 3. ]]
[[-0.66666667]
 [ 0.75      ]]


In [18]:
App = np.array([[0,0],[0,4]])
bpp = np.array([[0],[0]])

print(bpp-np.dot(Ap,xp)-np.dot(App,xr))
xpp = np.linalg.solve(Ar,bpp-np.dot(Ap,xp)-np.dot(App,xr))
print(xpp)

[[2.]
 [0.]]
[[0.66666667]
 [0.        ]]


In [19]:
0.6666666666*2

1.3333333332

In [20]:
4/alpha

4 - 4 * e([1]) + 4 * e([[1,2]]) - 4 * e([[1,3]]) + 4 * e([[1,4]]) - 4 * e([[1,5]])

In [21]:
x = oti.solve(A,b)
print(x)

[[0.16666667]
 [0.75      ]]
+ e([1]) * 
[[-0.66666667]
 [ 0.75      ]]
+ e([[1,2]]) * 
[[0.66666667]
 [0.        ]]
+ e([[1,3]]) * 
[[-0.66666667]
 [ 0.        ]]
+ e([[1,4]]) * 
[[0.66666667]
 [0.        ]]
+ e([[1,5]]) * 
[[-0.66666667]
 [ 0.        ]]



In [22]:
(4-3)/6

0.16666666666666666

In [13]:
display_string( oti.solve_latex(n_variables, deriv_order) ) 

<IPython.core.display.Math object>

In [37]:
%timeit x=(4-3*alpha)/(6*alpha)
x.get_deriv([[1,1]])

2.38 µs ± 8.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


-0.6666666666666666

In [8]:
b

omat< ndir: 0, order: 0>
re:
array([[2.],
       [3.]])

In [9]:
x = oti.solve(A,b)
print(x)

[[0.16666667]
 [0.75      ]]
+ e([1]) * 
[[-0.66666667]
 [ 0.75      ]]
+ e([2]) * 
[[0.]
 [0.]]
+ e([[1,2]]) * 
[[0.66666667]
 [0.        ]]
+ e([1,2]) * 
[[0.]
 [0.]]
+ e([[2,2]]) * 
[[0.]
 [0.]]
+ e([[1,3]]) * 
[[-0.66666667]
 [ 0.        ]]
+ e([[1,2],2]) * 
[[0.]
 [0.]]
+ e([1,[2,2]]) * 
[[0.]
 [0.]]
+ e([[2,3]]) * 
[[0.]
 [0.]]
+ e([[1,4]]) * 
[[0.66666667]
 [0.        ]]
+ e([[1,3],2]) * 
[[0.]
 [0.]]
+ e([[1,2],[2,2]]) * 
[[0.]
 [0.]]
+ e([1,[2,3]]) * 
[[0.]
 [0.]]
+ e([[2,4]]) * 
[[0.]
 [0.]]
+ e([[1,5]]) * 
[[-0.66666667]
 [ 0.        ]]
+ e([[1,4],2]) * 
[[0.]
 [0.]]
+ e([[1,3],[2,2]]) * 
[[0.]
 [0.]]
+ e([[1,2],[2,3]]) * 
[[0.]
 [0.]]
+ e([1,[2,4]]) * 
[[0.]
 [0.]]
+ e([[2,5]]) * 
[[0.]
 [0.]]



In [9]:
%timeit otic.dhelp_get_matrix_form(n_variables,deriv_order,export_sparse=True)

87.3 µs ± 1.58 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [14]:
441/6.47

68.16074188562597

In [11]:
b.get_im(0)
A.get_im(0)

array([[1., 0.],
       [0., 1.]])

In [12]:
matA = A.get_im(0)
matb = b.get_im(0)

In [13]:
%timeit oti.np.linalg.solve(matA,matb)

6.47 µs ± 31.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [77]:
from scipy.linalg import lu_factor, lu_solve

fact = lu_factor(matA)

%timeit lu_factor(matA)


6.68 s ± 690 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [78]:
%timeit lu_solve(fact,matb)

47.8 ms ± 791 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [79]:
%timeit lu_solve(lu_factor(matA),matb)

6.37 s ± 352 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [80]:
%timeit oti.np.dot(matA,matb)-matb

44 ms ± 2.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
idx_coo, ord_coo = dhelp_get_matrix_form(n_variables,deriv_order,export_sparse=True)

In [13]:
idx_coo.getnnz()

15

In [16]:
data = oti.np.arange(1,idx_coo.getnnz()+1)

In [15]:
idx_coo.row

array([0, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 3, 4, 4, 5], dtype=int32)

In [17]:
import scipy.sparse as spr

In [18]:
dummy_mat = spr.coo_matrix( (data,(idx_coo.row,idx_coo.col)) )

In [21]:

dummy_csr = dummy_mat.tocsr()



In [22]:
dummy_csr.data


array([ 1,  7,  2,  8,  3,  9, 12,  4, 10, 14, 13,  5, 11, 15,  6],
      dtype=int64)

In [25]:
indices = dummy_csr.data.copy()

In [29]:
# First system of equations

first_column = dummy_csr[:,0]

In [34]:
first_column.todense()
idx_coo.data[first_column.data-1],ord_coo.data[first_column.data-1]

(array([0, 0, 1, 0, 1, 2], dtype=uint64),
 array([0, 1, 1, 2, 2, 2], dtype=uint8))

In [28]:
dummy_csr[0]
dummy_csr[1]
dummy_csr[2]
dummy_csr[3]
dummy_csr[4]

<1x6 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [37]:
AA = A.get_im(0,copy=False)


In [38]:
A[1,1]=3

In [39]:
A

omat< ndir: 5, order: 2>
re:
array([[1., 0.],
       [0., 3.]])

In [40]:
AA


array([[1., 0.],
       [0., 3.]])