In [1]:
import spr_otilib as dn
e= dn.e
np = dn.np

In [2]:
a = 0*e(1) # 2 + 3*e([1,2]) + 20*e([1,3])
a

spr_otinum([], [], 1)

In [3]:
b = 0*e(1)#10 + 5*e([1,3])


In [4]:
A = np.array([a,b],dtype = dn.spr_otinum)
print(A)

[spr_otinum([], [], 1) spr_otinum([], [], 1)]


In [7]:
A_oti = dn.otivec(A,m=1)

In [8]:
print(A_oti.coefs.shape)
print(np.array(A_oti.coefs))


(2, 2)
[[ 0.  0.]
 [ 0.  0.]]


In [7]:
A_oti_p = dn.otivec(A_oti.coefs,m =A_oti.m,order = A_oti.maxorder)

In [8]:
A_oti_p.coefs.shape

(2, 10)

In [9]:
A_oti_p

< otivec with  2 oti numbers of order 2 and 3 basis >

In [10]:
print(A_oti_p)

[  2.0 + 3.0 * e([1,2]) + 20.0 * e([1,3]) ,
  10.0 + 5.0 * e([1,3]) ]


In [11]:

print(np.array(A_oti_p.getDual([1,3])))

#dn.h.findIndx(np.array([1,3],dtype = np.uint16),np.array([1,1],dtype = np.uint16),np.uint8(2))

[ 20.   5.]


In [12]:
A_oti_p.setDual([[2,2]],np.array([3,4],dtype = np.float64))

print(A_oti_p)

[  2.0 + 3.0 * e([1,2]) + 3.0 * e([[2,2]]) + 20.0 * e([1,3]) ,
  10.0 + 4.0 * e([[2,2]]) + 5.0 * e([1,3]) ]


In [13]:
np.array(A_oti_p.getDeriv([[2,2]]))

array([ 6.,  8.])

In [14]:
np.array((1,2,3,4,45))

array([ 1,  2,  3,  4, 45])

In [15]:
B = np.zeros((2,2)).astype(dn.spr_otinum)
B[0,0] = a
print(B)

[[spr_otinum([0,4,7], [2.,3.,20.], 2) 0.0]
 [0.0 0.0]]


In [24]:
A = dn.otimat((2,2),A_oti.m,A_oti.maxorder,2)

In [25]:
A

< otimat of shape (2,2) with oti numbers of order 2 and 3 basis >

In [26]:
print(A)

< otimat of shape (2,2) with oti numbers of order 2 and 3 basis: 
[  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2

In [27]:
A[1,1] = A_oti_p[1]
A[0,0] = A_oti_p[0]

In [28]:
print(A)

< otimat of shape (2,2) with oti numbers of order 2 and 3 basis: 
[  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in LInked List format>,
  <2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>,
  <2x2

In [29]:
print(A.ndir)
print(" ")

for i in range(A.ndir):
    print(A[i].toarray())
    print(" ")


10
 
[[  2.   0.]
 [  0.  10.]]
 
[[ 0.  0.]
 [ 0.  0.]]
 
[[ 0.  0.]
 [ 0.  0.]]
 
[[ 0.  0.]
 [ 0.  0.]]
 
[[ 3.  0.]
 [ 0.  0.]]
 
[[ 3.  0.]
 [ 0.  4.]]
 
[[ 0.  0.]
 [ 0.  0.]]
 
[[ 20.   0.]
 [  0.   5.]]
 
[[ 0.  0.]
 [ 0.  0.]]
 
[[ 0.  0.]
 [ 0.  0.]]
 


In [ ]:
class myTestClass:
    def __init__(self):
        self.j = 0
    def __getitem__(self,index):
        print(index)
        print(type(index))
        print(type(index) == slice)
        

In [ ]:
a = myTestClass()
a[b]

In [ ]:
b*0

In [ ]:
str(dn.spr.coo_matrix((3,4)))

In [ ]:
m = 6
n = 3
dn.comb(m+n,m,exact = True)