In [1]:
import sys
path2oti = '../../../build/'
sys.path.append(path2oti) # Add path to OTI library.
import pyoti.sparse as dn 

e = dn.e
dn.np.set_printoptions(precision=4)
np = dn.np

import sympy as sym
# sym.init_printing()

In [4]:
x_t  = 0.5 + e(1, order = 10, nbases = 2)
y_t  = 1.5 + e(2, order = 10, nbases = 2)
print(x_t)

0.5 + 1 * e([1])


In [5]:
x_t*y_t

0.7500 + 1.5000 * e([1]) + 0.5000 * e([2]) + 1.0000 * e([1,2])

In [6]:
x_t/y_t

0.3333 + 0.6667 * e([1]) - 0.2222 * e([2]) - 0.4444 * e([1,2]) + 0.1481 * e([[2,2]]) + 0.2963 * e([1,[2,2]]) - 0.0988 * e([[2,3]]) - 0.1975 * e([1,[2,3]]) + 0.0658 * e([[2,4]]) + 0.1317 * e([1,[2,4]]) - 0.0439 * e([[2,5]]) - 0.0878 * e([1,[2,5]]) + 0.0293 * e([[2,6]]) + 0.0585 * e([1,[2,6]]) - 0.0195 * e([[2,7]]) - 0.0390 * e([1,[2,7]]) + 0.0130 * e([[2,8]]) + 0.0260 * e([1,[2,8]]) - 0.0087 * e([[2,9]]) - 0.0173 * e([1,[2,9]]) + 0.0058 * e([[2,10]])

In [7]:
1/y_t

0.6667 - 0.4444 * e([2]) + 0.2963 * e([[2,2]]) - 0.1975 * e([[2,3]]) + 0.1317 * e([[2,4]]) - 0.0878 * e([[2,5]]) + 0.0585 * e([[2,6]]) - 0.0390 * e([[2,7]]) + 0.0260 * e([[2,8]]) - 0.0173 * e([[2,9]]) + 0.0116 * e([[2,10]])

In [6]:
fx = dn.atan2(x_t,y_t)
fx

otinum([0.3217505543966422,0.5999999999999999, ..., -7.766016000017573e-05,0.010210508800005519,], 10)

In [7]:
fx.get_deriv([[1,1]])
fx.get_deriv([[1,2]])
fx.get_deriv([[1,3]])
fx.get_deriv([[1,3],[2,7]])

-3705.189433343598

In [8]:
x0s,b, y0s = sym.symbols("x0,b,y0")
np.float(sym.diff(sym.atan(x0s/y0s),y0s,7).diff(x0s,3).replace(x0s,0.5).replace(y0s,1.5))

-3705.189433344002

In [9]:
for i in range(0,11):
#     print("\n\n -------------------------- ")
    print(" ")
#     print("Order: ",i)
    print(sym.ccode(sym.diff(sym.atan(x0s),x0s,i)))
    

 
atan(x0)
 
1.0/(pow(x0, 2) + 1)
 
-2*x0/pow(pow(x0, 2) + 1, 2)
 
2*(4*pow(x0, 2)/(pow(x0, 2) + 1) - 1)/pow(pow(x0, 2) + 1, 2)
 
24*x0*(-2*pow(x0, 2)/(pow(x0, 2) + 1) + 1)/pow(pow(x0, 2) + 1, 3)
 
24*(16*pow(x0, 4)/pow(pow(x0, 2) + 1, 2) - 12*pow(x0, 2)/(pow(x0, 2) + 1) + 1)/pow(pow(x0, 2) + 1, 3)
 
240*x0*(-16*pow(x0, 4)/pow(pow(x0, 2) + 1, 2) + 16*pow(x0, 2)/(pow(x0, 2) + 1) - 3)/pow(pow(x0, 2) + 1, 4)
 
720*(64*pow(x0, 6)/pow(pow(x0, 2) + 1, 3) - 80*pow(x0, 4)/pow(pow(x0, 2) + 1, 2) + 24*pow(x0, 2)/(pow(x0, 2) + 1) - 1)/pow(pow(x0, 2) + 1, 4)
 
40320*x0*(-16*pow(x0, 6)/pow(pow(x0, 2) + 1, 3) + 24*pow(x0, 4)/pow(pow(x0, 2) + 1, 2) - 10*pow(x0, 2)/(pow(x0, 2) + 1) + 1)/pow(pow(x0, 2) + 1, 5)
 
40320*(256*pow(x0, 8)/pow(pow(x0, 2) + 1, 4) - 448*pow(x0, 6)/pow(pow(x0, 2) + 1, 3) + 240*pow(x0, 4)/pow(pow(x0, 2) + 1, 2) - 40*pow(x0, 2)/(pow(x0, 2) + 1) + 1)/pow(pow(x0, 2) + 1, 5)
 
725760*x0*(-256*pow(x0, 8)/pow(pow(x0, 2) + 1, 4) + 512*pow(x0, 6)/pow(pow(x0, 2) + 1, 3) - 336*pow(x0, 4)/

In [10]:

np.arccosh(1.5)

0.96242365011920694

In [17]:
aRe,ae1,ae2,ae3 = sym.symbols("a_Re,a_e1,a_e2,a_e3")
M = sym.Matrix([[aRe,0,0],[ae1,aRe,0],[ae2,0,aRe]])

In [18]:
M

Matrix([
[a_Re,    0,    0],
[a_e1, a_Re,    0],
[a_e2,    0, a_Re]])

In [29]:
M.eigenvects()

[(a_Re, 3, [Matrix([
   [0],
   [1],
   [0]]), Matrix([
   [0],
   [0],
   [1]])])]

In [19]:
M.inv()

Matrix([
[       1/a_Re,      0,      0],
[-a_e1/a_Re**2, 1/a_Re,      0],
[-a_e2/a_Re**2,      0, 1/a_Re]])

In [13]:
def factorialfunct(n):
    nn = np.uint64(n)
    res = np.uint64(1)
    
    for i in range(n):
        res*=nn
        nn-=1
    print(res)
        


In [17]:
factorialfunct(100)

9.33262154439e+157


In [20]:
def oticomb(m,n):
    mm = np.uint64(m)
    mpn_res = np.uint64(1)
    nn = np.uint64(n)
    n_res = np.uint64(1)
    for i in range(n):
        mpn_res *=(mm+nn)
        n_res   *= nn
        nn-=1
    print(np.uint64(mpn_res/n_res))

In [40]:
oticomb(3,5)


56


In [49]:
dn.findComb(2+1,10)

66

In [45]:
x_t.Ndir

66

In [12]:
a = 2+2*e(1,order = 2,m=2)

In [43]:
np.array(range(1,dn.findComb(20+1,2)+1))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [48]:

a = dn.otinum(np.array(range(1,dn.findComb(20+1,2)+1),dtype = np.double),2)
a.toMatrix()
print(a.coefs)

[   1.    2.    3.    4.    5.    6.    7.    8.    9.   10.   11.   12.
   13.   14.   15.   16.   17.   18.   19.   20.   21.   22.   23.   24.
   25.   26.   27.   28.   29.   30.   31.   32.   33.   34.   35.   36.
   37.   38.   39.   40.   41.   42.   43.   44.   45.   46.   47.   48.
   49.   50.   51.   52.   53.   54.   55.   56.   57.   58.   59.   60.
   61.   62.   63.   64.   65.   66.   67.   68.   69.   70.   71.   72.
   73.   74.   75.   76.   77.   78.   79.   80.   81.   82.   83.   84.
   85.   86.   87.   88.   89.   90.   91.   92.   93.   94.   95.   96.
   97.   98.   99.  100.  101.  102.  103.  104.  105.  106.  107.  108.
  109.  110.  111.  112.  113.  114.  115.  116.  117.  118.  119.  120.
  121.  122.  123.  124.  125.  126.  127.  128.  129.  130.  131.  132.
  133.  134.  135.  136.  137.  138.  139.  140.  141.  142.  143.  144.
  145.  146.  147.  148.  149.  150.  151.  152.  153.  154.  155.  156.
  157.  158.  159.  160.  161.  162.  163.  164.  1

In [14]:
b = 3+e(2,order = 2,m=2)

In [34]:
a*b

otinum([3.0,6.0,9.0,13.0,17.0,22.0], 2)

In [35]:
%timeit a*b

546 ns ± 26.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [40]:
dn.findComb(20+1,2)#*8/1024/1024 # --> MB

231

In [54]:
%timeit mat = dn.OTI_GEN_INDX_MatForm(30,2)
csr_mat = mat.tocsr()
# mat.todense()

1.83 ms ± 8.39 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
mat.data.size

15

In [24]:
mat.shape


(6, 6)

In [25]:
mat.data

array([1, 2, 3, 4, 5, 6, 1, 2, 4, 1, 1, 2, 4, 1, 1], dtype=uint64)

In [26]:
mat.todense()

matrix([[1, 0, 0, 0, 0, 0],
        [2, 1, 0, 0, 0, 0],
        [3, 2, 1, 0, 0, 0],
        [4, 0, 0, 1, 0, 0],
        [5, 4, 0, 2, 1, 0],
        [6, 0, 0, 4, 0, 1]], dtype=uint64)

In [31]:
csr_a = dn.spr.csr_matrix(a.toMatrix())

In [36]:
vec_b = b.coefs
%timeit csr_a.dot(vec_b)

5.39 µs ± 75.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# Quadrature integration


def quadrature_int():

In [20]:
y = sym.Function('y')(x0s)
y

y(x0)

In [22]:
sym.diff(y,x0s,2).doit()

Derivative(y(x0), x0, x0)