In [1]:
import pstats, cProfile
from line_profiler import LineProfiler

import spr_otilib as oti
e = oti.e
np = oti.np
spr = oti.spr

In [2]:
import math

In [3]:
oti.h.getNels(10,2)
error = np.zeros(1,dtype = np.uint8)
oti.h.multIndx(1,10,2,error)
print(error)

[0]


In [4]:
expMax = 10
dirMax = 10
ggg = ''
for i in range(dirMax+1):
    
    for j in range(expMax+1):
        ggg+= str(i**j)+", "
    ggg+='\n'
        
print(ggg)

1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 
1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683, 59049, 
1, 4, 16, 64, 256, 1024, 4096, 16384, 65536, 262144, 1048576, 
1, 5, 25, 125, 625, 3125, 15625, 78125, 390625, 1953125, 9765625, 
1, 6, 36, 216, 1296, 7776, 46656, 279936, 1679616, 10077696, 60466176, 
1, 7, 49, 343, 2401, 16807, 117649, 823543, 5764801, 40353607, 282475249, 
1, 8, 64, 512, 4096, 32768, 262144, 2097152, 16777216, 134217728, 1073741824, 
1, 9, 81, 729, 6561, 59049, 531441, 4782969, 43046721, 387420489, 3486784401, 
1, 10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000, 10000000000, 



In [1]:
pows = [1,  0,   0,    0,     0,      0,       0,        0,         0,          0,           0,  
        1,  1,   1,    1,     1,      1,       1,        1,         1,          1,           1, 
        1,  2,   4,    8,    16,     32,      64,      128,       256,        512,        1024, 
        1,  3,   9,   27,    81,    243,     729,     2187,      6561,      19683,       59049,  
        1,  4,  16,   64,   256,   1024,    4096,    16384,     65536,     262144,     1048576,  
        1,  5,  25,  125,   625,   3125,   15625,    78125,    390625,    1953125,     9765625,  
        1,  6,  36,  216,  1296,   7776,   46656,   279936,   1679616,   10077696,    60466176,  
        1,  7,  49,  343,  2401,  16807,  117649,   823543,   5764801,   40353607,   282475249,  
        1,  8,  64,  512,  4096,  32768,  262144,  2097152,  16777216,  134217728,  1073741824,  
        1,  9,  81,  729,  6561,  59049,  531441,  4782969,  43046721,  387420489,  3486784401,  
        1, 10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000, 10000000000]

In [2]:
base = 8
exp = 5
%timeit pows[base*11+exp]
%timeit base**exp

print(pows[base*11+exp])
base**exp

The slowest run took 9.50 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 116 ns per loop
The slowest run took 4.96 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 336 ns per loop
32768


32768

In [15]:
m=50
o=2

%timeit np.sin(2)
%timeit math.sin(2)

In [4]:
(2**64-1)/(16**16) 

1.0

In [3]:
def multTest(a,b):
    return a*b

In [6]:
oti.getDirArray(4,2)

[1, 2]

In [16]:


a = 3 +  e( 1,m=m,maxorder=o)

('DirA: ', array([1, 0], dtype=uint16))
('ExpA: ', array([1, 0], dtype=uint8))
('Index: ', 1)
2


In [8]:
a.getDual(1)

1.0

In [7]:
print(a)

3.0 + 1.0 * e([1]) + 0.0 * e([[1,2]]) + 0.0 * e([2]) + 0.0 * e([1,2]) + 0.0 * e([[2,2]]) 


In [8]:
error = np.ones(1,dtype = np.uint8)
print(oti.h.multIndx(1,1,2,error))
print(error)

2
[0]


In [9]:
a*a

otinum([9.,6.,1.,0.,0.,0.], 2)

In [10]:
print(a)

3.0 + 1.0 * e([1]) + 0.0 * e([[1,2]]) + 0.0 * e([2]) + 0.0 * e([1,2]) + 0.0 * e([[2,2]]) 


In [11]:
prof = LineProfiler(a.__mul__)
prof.runcall(a.__mul__,a)
prof.print_stats()

Timer unit: 1e-06 s



/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Could not extract a code object for the object <method-wrapper '__mul__' of spr_otilib.otinum object at 0x108a85318>
  if __name__ == '__main__':


In [14]:
a

otinum([3.,1.,0.,0.,0.,0.], 2)

In [15]:
prof.print_stats()

Timer unit: 1e-06 s



In [17]:
cProfile.run("a*a")

         15833870 function calls (14075594 primitive calls) in 5.489 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    5.489    5.489 <string>:1(<module>)
        1    2.068    2.068    5.489    5.489 spr_otilib.pyx:1214(__mul__)
        2    0.000    0.000    0.000    0.000 spr_otilib.pyx:1430(copy)
        2    0.000    0.000    0.000    0.000 spr_otilib.pyx:538(__cinit__)
3516552/1758276    0.661    0.000    0.661    0.000 spr_otilib.pyx:9664(multIndx)
        4    0.000    0.000    0.000    0.000 stringsource:1092(abs_py_ssize_t)
        2    0.000    0.000    0.000    0.000 stringsource:1099(get_best_order)
        2    0.000    0.000    0.000    0.000 stringsource:1160(slice_get_size)
        2    0.000    0.000    0.000    0.000 stringsource:1171(fill_contig_strides_array)
        2    0.000    0.000    0.000    0.000 stringsource:120(__cinit__)
        2    0.000    0.000    0.000    0.0

In [12]:
cProfile.run("a.mult(a)")

         15886318 function calls in 5.342 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    5.342    5.342 <string>:1(<module>)
        1    2.077    2.077    5.342    5.342 spr_otilib.pyx:2098(mult)
     5151    0.002    0.000    0.009    0.000 spr_otilib.pyx:533(__get__)
  1758276    0.476    0.000    0.711    0.000 spr_otilib.pyx:9662(multIndx (wrapper))
  1758276    0.235    0.000    0.235    0.000 spr_otilib.pyx:9662(multIndx)
  1763430    0.231    0.000    0.231    0.000 stringsource:294(align_pointer)
  1763430    0.497    0.000    0.729    0.000 stringsource:341(__cinit__)
  1763430    0.203    0.000    0.203    0.000 stringsource:368(__dealloc__)
     5151    0.002    0.000    0.002    0.000 stringsource:385(get_item_pointer)
     5151    0.004    0.000    0.009    0.000 stringsource:395(__getitem__)
  1758276    0.151    0.000    0.151    0.000 stringsource:545(__get__)
        1    0.

In [55]:
a.mult(a)
a

otinum([9.,6.,1.,...,0.,0.,0.], 2)

In [11]:
b = 10+ e( 2, m=m, maxorder=o)
b.getDual(2)

('DirA: ', array([2, 0], dtype=uint16))
('ExpA: ', array([1, 0], dtype=uint8))
('Index: ', 3)
2


1.0

In [12]:
a*b

otinum([30.,10.,0.,...,0.,0.,0.], 2)

In [13]:
a*b

%timeit a*a # SUPER SLOW ! --> Need to speed up a LOT. 

# Goal: Multiply in Less than 1 us for order 1 and less than 4 us for order 2 and up

# TODO: Modify the multiplication so that it only takes the multiples of the resulting directions 
# Order 1 : 19.1 us
# Order 2 : 48.3 us  fast ->  40.6 us.




1 loop, best of 3: 1.21 s per loop


In [8]:
a.mult(b)

a

otinum([30.,10.,3.], 1)

In [15]:
%timeit -n10 a.mult(b)

10 loops, best of 3: 965 ms per loop


In [21]:
# dirA = np.array([1,20,0,0,0,0,0,0,0,0],dtype = np.uint16)
# expA = np.array([1, 1,0,0,0,0,0,0,0,0],dtype = np.uint8 )
# %timeit -n10 oti.h.findIndx(dirA, expA, 10)   # 2.77 us <- fastpow  
#                                               # 5.08 us <- pow   (order 2)

indx = 10
order = 3
dirA = oti.h.getDirA(indx,order)
expA = oti.h.getExpA(indx,order)
%timeit -n10 oti.h.findIndx(dirA, expA, order)# 2.77 us <- fastpow  
                                              # 5.08 us <- pow   (order 2)
# Search for:
print("Search for:")
print(dirA.base)
print(expA.base)
indxF = oti.h.findIndx(dirA, expA, order)
print("Found:")
print(oti.h.getDirA(indxF,order).base)
print(oti.h.getExpA(indxF,order).base)

10 loops, best of 3: 770 ns per loop
Search for:
[3 0 0]
[1 0 0]
Found:
[3 0 0]
[1 0 0]


In [ ]:
a_spr = oti.spr_otinum(np.array([0,1],dtype = np.uint64),np.array([2,1],dtype = np.float64),o)

In [ ]:
print(a_spr)

In [ ]:
b_spr = oti.spr_otinum(np.array([0,6],dtype = np.uint64),np.array([10,1],dtype = np.float64),o)

In [ ]:
print(b_spr)

In [ ]:
print(repr(a_spr))
print(repr(b_spr))
a_spr*b_spr

In [ ]:
%timeit a_spr*b_spr

In [ ]:
A = a_spr.toMatrix(m=m)
B = b_spr.toMatrix(m=m)

In [ ]:
A

In [ ]:
B

In [ ]:
%timeit np.dot(A,B[:,0])

In [ ]:
A_spr = spr.csr_matrix(A)
B_spr = spr.csr_matrix(B)

In [ ]:
%timeit A_spr*B_spr

In [ ]:
oti.number_types

In [ ]:
a = 3.5

%timeit type(a) in oti.number_types