In [2]:
# 1. SET GLOBAL PATH 
import sys
path2oti = '../'
sys.path.append(path2oti) # Add path to OTI library.


# 2. OTI LIBRARY
import otilib as oti
np = oti.np
e = oti.e

In [11]:
x = 3.5+e(100)

In [13]:
x.coefs

array([3.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. ])

In [20]:
b = (x**10)

In [21]:
b.coefs

array([275854.73535156,      0.        ,      0.        ,      0.        ,
            0.        ,      0.        ,      0.        ,      0.        ,
            0.        ,      0.        ,      0.        ,      0.        ,
            0.        ,      0.        ,      0.        ,      0.        ,
            0.        ,      0.        ,      0.        ,      0.        ,
            0.        ,      0.        ,      0.        ,      0.        ,
            0.        ,      0.        ,      0.        ,      0.        ,
            0.        ,      0.        ,      0.        ,      0.        ,
            0.        ,      0.        ,      0.        ,      0.        ,
            0.        ,      0.        ,      0.        ,      0.        ,
            0.        ,      0.        ,      0.        ,      0.        ,
            0.        ,      0.        ,      0.        ,      0.        ,
            0.        ,      0.        ,      0.        ,      0.        ,
            0.        ,  

In [8]:

oti.cos(x**10)

otinum([-0.6143631087135087,621873.854408028], 1)

In [10]:
-np.sin(3.5**10)*10*3.5**9

621873.854408028

In [14]:
se = oti.se

In [22]:

x_s = 3.5+se(100,order = 2)

In [28]:
bs = x_s**10
print(bs.coefs)

[ 275854.73535156  788156.38671875 1013343.92578125]


In [27]:
10*9*3.5**8/2

1013343.92578125